const STORE_KEY='sylvarts_bms_v3';
const SESSION_KEY='sylvarts_demo_session_v3';
const DEMO_PASSWORD='demo123';

const seed={
  products:[
    {id:1,sku:'SFC-HL-001',name:'Classic Pink Heel',category:'Heels',emoji:'👠',cost:65000,price:120000,variants:[{id:'1a',size:'37',color:'Pink',stock:2,reorder:2},{id:'1b',size:'38',color:'Pink',stock:1,reorder:2},{id:'1c',size:'39',color:'Pink',stock:4,reorder:2},{id:'1d',size:'40',color:'Black',stock:2,reorder:2}]},
    {id:2,sku:'SFC-HB-004',name:'Structured Handbag',category:'Handbags',emoji:'👜',cost:82000,price:155000,variants:[{id:'2a',size:'One size',color:'Black',stock:2,reorder:2},{id:'2b',size:'One size',color:'Pink',stock:1,reorder:2},{id:'2c',size:'One size',color:'Tan',stock:3,reorder:2}]},
    {id:3,sku:'SFC-DR-011',name:'Evening Dress',category:'Dresses',emoji:'👗',cost:105000,price:220000,variants:[{id:'3a',size:'S',color:'Black',stock:2,reorder:1},{id:'3b',size:'M',color:'Black',stock:3,reorder:2},{id:'3c',size:'L',color:'Wine',stock:2,reorder:1}]},
    {id:4,sku:'SFC-SN-007',name:'Urban Sneaker',category:'Shoes',emoji:'👟',cost:70000,price:135000,variants:[{id:'4a',size:'38',color:'White',stock:0,reorder:2},{id:'4b',size:'39',color:'White',stock:1,reorder:2},{id:'4c',size:'40',color:'White',stock:2,reorder:2},{id:'4d',size:'41',color:'Black',stock:1,reorder:2}]},
    {id:5,sku:'SFC-AC-015',name:'Statement Necklace',category:'Accessories',emoji:'📿',cost:24000,price:55000,variants:[{id:'5a',size:'One size',color:'Gold',stock:8,reorder:3},{id:'5b',size:'One size',color:'Silver',stock:7,reorder:3}]},
    {id:6,sku:'SFC-SD-012',name:'Signature Sandal',category:'Sandals',emoji:'👡',cost:52000,price:98000,variants:[{id:'6a',size:'37',color:'Tan',stock:2,reorder:2},{id:'6b',size:'38',color:'Tan',stock:1,reorder:2},{id:'6c',size:'39',color:'Black',stock:2,reorder:2}]},
    {id:7,sku:'SFC-BG-009',name:'Mini Crossbody Bag',category:'Handbags',emoji:'🎒',cost:54000,price:110000,variants:[{id:'7a',size:'One size',color:'Pink',stock:4,reorder:2},{id:'7b',size:'One size',color:'Black',stock:4,reorder:2},{id:'7c',size:'One size',color:'Cream',stock:3,reorder:2}]},
    {id:8,sku:'SFC-SK-018',name:'Pleated Midi Skirt',category:'Skirts',emoji:'🩱',cost:46000,price:95000,variants:[{id:'8a',size:'S',color:'Black',stock:2,reorder:1},{id:'8b',size:'M',color:'Black',stock:2,reorder:1},{id:'8c',size:'L',color:'Olive',stock:2,reorder:1}]}
  ],
  customers:[
    {id:1,name:'Amina N.',phone:'+256 772 440 811',email:'amina@example.com',segment:'VIP',joined:'2026-06-18'},
    {id:2,name:'Sharon K.',phone:'+256 701 282 410',email:'sharon@example.com',segment:'Regular',joined:'2026-07-02'},
    {id:3,name:'Kampala Style Hub',phone:'+256 755 020 118',email:'orders@kampalastyle.demo',segment:'Wholesale',joined:'2026-05-20'},
    {id:4,name:'Mirembe Boutique',phone:'+256 782 519 222',email:'mirembe@example.com',segment:'Wholesale',joined:'2026-04-11'}
  ],
  suppliers:[
    {id:1,name:'Pearl Footwear Supply',contact:'Sarah N.',phone:'+256 755 108 300',email:'supply@pearl.demo',lead:5,categories:'Heels, Sandals, Shoes'},
    {id:2,name:'Kampala Fashion Imports',contact:'Moses K.',phone:'+256 701 640 227',email:'orders@kfi.demo',lead:7,categories:'Handbags, Accessories'},
    {id:3,name:'StyleSource Textiles',contact:'Ruth A.',phone:'+256 772 913 021',email:'trade@stylesource.demo',lead:10,categories:'Dresses, Skirts'}
  ],
  sales:[
    {id:'S-1048',receipt:'RCT-1048',date:'2026-08-20T09:18:00',customerId:null,customer:'Walk-in Customer',method:'Mobile Money',discount:0,items:[{productId:1,variantId:'1a',name:'Classic Pink Heel',variant:'37 • Pink',qty:1,price:120000,cost:65000}],total:120000},
    {id:'S-1047',receipt:'RCT-1047',date:'2026-08-20T08:42:00',customerId:1,customer:'Amina N.',method:'Cash',discount:0,items:[{productId:5,variantId:'5a',name:'Statement Necklace',variant:'One size • Gold',qty:2,price:55000,cost:24000}],total:110000},
    {id:'S-1046',receipt:'RCT-1046',date:'2026-08-19T16:05:00',customerId:2,customer:'Sharon K.',method:'Mobile Money',discount:0,items:[{productId:3,variantId:'3b',name:'Evening Dress',variant:'M • Black',qty:1,price:220000,cost:105000}],total:220000},
    {id:'S-1045',receipt:'RCT-1045',date:'2026-08-19T12:27:00',customerId:null,customer:'Walk-in Customer',method:'Cash',discount:0,items:[{productId:6,variantId:'6a',name:'Signature Sandal',variant:'37 • Tan',qty:1,price:98000,cost:52000}],total:98000}
  ],
  invoices:[
    {id:'INV-2026-018',date:'2026-08-20',customerId:3,customer:'Kampala Style Hub',due:'2026-08-27',status:'Pending',items:[{description:'Structured Handbag • Mixed colours',qty:3,price:155000}],amount:465000},
    {id:'INV-2026-017',date:'2026-08-18',customerId:4,customer:'Mirembe Boutique',due:'2026-08-25',status:'Paid',items:[{description:'Fashion stock order',qty:1,price:320000}],amount:320000},
    {id:'INV-2026-016',date:'2026-08-17',customerId:null,customer:'Private Client',due:'2026-08-24',status:'Draft',items:[{description:'Custom order',qty:1,price:185000}],amount:185000}
  ],
  purchaseOrders:[
    {id:'PO-2026-012',supplierId:1,supplier:'Pearl Footwear Supply',date:'2026-08-18',status:'Ordered',eta:'2026-08-23',items:[{productId:4,variantId:'4a',description:'Urban Sneaker • 38 • White',qty:8,cost:70000}],total:560000},
    {id:'PO-2026-011',supplierId:2,supplier:'Kampala Fashion Imports',date:'2026-08-12',status:'Received',eta:'2026-08-17',items:[{productId:2,variantId:'2b',description:'Structured Handbag • Pink',qty:6,cost:82000}],total:492000}
  ],
  expenses:[
    {id:'EXP-0092',date:'2026-08-20',category:'Packaging',description:'Premium shopping bags & tissue',amount:68000,method:'Mobile Money'},
    {id:'EXP-0091',date:'2026-08-19',category:'Transport',description:'Supplier collection transport',amount:45000,method:'Cash'},
    {id:'EXP-0090',date:'2026-08-18',category:'Marketing',description:'TikTok content boost',amount:120000,method:'Mobile Money'},
    {id:'EXP-0089',date:'2026-08-17',category:'Utilities',description:'Shop utilities allocation',amount:85000,method:'Cash'}
  ],
  users:[
    {id:1,name:'Sylvarts Owner',email:'owner@sylvarts.demo',role:'owner',active:true},
    {id:2,name:'Store Manager',email:'manager@sylvarts.demo',role:'manager',active:true},
    {id:3,name:'Sales Staff',email:'sales@sylvarts.demo',role:'sales',active:true}
  ],
  activity:[
    {type:'sale',title:'Sale S-1048 completed',detail:'Classic Pink Heel • Mobile Money',time:'Today, 09:18'},
    {type:'stock',title:'Size 38 Pink Heel reached reorder level',detail:'1 unit remains • threshold 2',time:'Today, 09:18'},
    {type:'invoice',title:'Invoice INV-2026-018 created',detail:'Kampala Style Hub • UGX 465,000',time:'Today, 08:20'},
    {type:'purchase',title:'PO-2026-012 sent to supplier',detail:'Urban Sneaker Size 38 • 8 units',time:'18 Aug'},
    {type:'expense',title:'Packaging expense recorded',detail:'UGX 68,000',time:'Today, 07:55'}
  ],
  daily:[180000,260000,210000,340000,295000,410000,520000,380000,610000,560000,690000,548000]
};

const roleConfig={
  owner:{label:'Owner / Admin',name:'Sylvarts Owner',initials:'SO',views:['dashboard','pos','inventory','customers','suppliers','purchasing','receipts','invoices','expenses','tracking','reports','settings']},
  manager:{label:'Manager',name:'Store Manager',initials:'SM',views:['dashboard','pos','inventory','customers','suppliers','purchasing','receipts','invoices','expenses','tracking','reports']},
  sales:{label:'Sales Staff',name:'Sales Staff',initials:'SS',views:['dashboard','pos','inventory','customers','receipts']}
};
const navDefs=[
  ['dashboard','Dashboard','<svg viewBox="0 0 24 24"><rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/></svg>'],
  ['pos','Point of Sale','<svg viewBox="0 0 24 24"><path d="M4 6h16v12H4z"/><path d="M8 10h8M8 14h3"/></svg>'],
  ['inventory','Inventory','<svg viewBox="0 0 24 24"><path d="M4 7h16M4 12h16M4 17h16"/><path d="M7 4v16M17 4v16"/></svg>'],
  ['customers','Customers','<svg viewBox="0 0 24 24"><circle cx="9" cy="8" r="3"/><path d="M3 20c0-4 2-7 6-7s6 3 6 7"/><circle cx="17" cy="9" r="2"/><path d="M16 14c3 0 5 2 5 5"/></svg>'],
  ['suppliers','Suppliers','<svg viewBox="0 0 24 24"><path d="M3 10h13v9H3z"/><path d="M16 13h3l2 3v3h-5z"/><circle cx="7" cy="20" r="1.5"/><circle cx="18" cy="20" r="1.5"/></svg>'],
  ['purchasing','Purchasing','<svg viewBox="0 0 24 24"><path d="M4 5h2l2 10h10l2-7H7"/><circle cx="10" cy="19" r="1"/><circle cx="18" cy="19" r="1"/></svg>'],
  ['receipts','Receipts','<svg viewBox="0 0 24 24"><path d="M6 3h12v18l-3-2-3 2-3-2-3 2z"/><path d="M9 8h6M9 12h6M9 16h4"/></svg>'],
  ['invoices','Invoices','<svg viewBox="0 0 24 24"><path d="M6 2h9l4 4v16H6z"/><path d="M14 2v5h5M9 12h6M9 16h6"/></svg>'],
  ['expenses','Expenses','<svg viewBox="0 0 24 24"><path d="M4 6h16v13H4z"/><path d="M4 10h16M8 15h4"/></svg>'],
  ['tracking','Tracking','<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="3"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3"/></svg>'],
  ['reports','Reports','<svg viewBox="0 0 24 24"><path d="M4 20V10m5 10V4m5 16v-7m5 7V7"/></svg>'],
  ['settings','Admin & Settings','<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="3"/><path d="M12 2v3M12 19v3M4.9 4.9 7 7m10 10 2.1 2.1M2 12h3m14 0h3M4.9 19.1 7 17m10-10 2.1-2.1"/></svg>']
];

let db=loadDb();
let session=loadSession();
let currentView='dashboard';
let saleCart=[];
let invoiceCart=[];
let posSearch='';
let posCategory='All';
let tourIndex=0;

function clone(x){return JSON.parse(JSON.stringify(x))}
function loadDb(){try{return JSON.parse(localStorage.getItem(STORE_KEY))||clone(seed)}catch{return clone(seed)}}
function saveDb(){localStorage.setItem(STORE_KEY,JSON.stringify(db))}
function loadSession(){try{return JSON.parse(sessionStorage.getItem(SESSION_KEY))}catch{return null}}
function saveSession(){sessionStorage.setItem(SESSION_KEY,JSON.stringify(session))}
function money(n){return 'UGX '+Math.round(Number(n||0)).toLocaleString('en-UG')}
function fmtDate(v){const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleDateString('en-UG',{day:'2-digit',month:'short',year:'numeric'})}
function nowLabel(){return new Date().toLocaleString('en-UG',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})}
function uid(prefix){return `${prefix}-${String(Date.now()).slice(-6)}`}
function totalStock(p){return p.variants.reduce((a,v)=>a+Number(v.stock||0),0)}
function lowVariants(){return db.products.flatMap(p=>p.variants.filter(v=>v.stock<=v.reorder).map(v=>({product:p,variant:v})))}
function productById(id){return db.products.find(p=>p.id===Number(id))}
function variantById(p,id){return p?.variants.find(v=>v.id===id)}
function customerById(id){return db.customers.find(c=>c.id===Number(id))}
function supplierById(id){return db.suppliers.find(s=>s.id===Number(id))}
function role(){return roleConfig[session?.role||'owner']}
function can(view){return role().views.includes(view)}
function toast(msg,type='good'){const w=document.getElementById('toastWrap');const e=document.createElement('div');e.className=`toast ${type}`;e.textContent=msg;w.appendChild(e);setTimeout(()=>e.remove(),3200)}
function stockBadge(v){if(v.stock<=0)return ['Out','badge-out'];if(v.stock<=v.reorder)return ['Low','badge-low'];return ['OK','badge-ok']}
function productStockState(p){const s=totalStock(p);const lows=p.variants.filter(v=>v.stock<=v.reorder).length;if(s===0)return ['Out of stock','badge-out'];if(lows)return [`${lows} variant${lows>1?'s':''} low`,'badge-low'];return ['Healthy','badge-ok']}
function addActivity(type,title,detail){db.activity.unshift({type,title,detail,time:nowLabel()});db.activity=db.activity.slice(0,20)}
function closeModal(){document.getElementById('modalBackdrop').classList.add('hidden')}
function openModal(html,wide=false){const b=document.getElementById('modalBackdrop');const m=document.getElementById('modal');m.className='modal'+(wide?' wide':'');m.innerHTML=html;b.classList.remove('hidden')}
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}

window.addEventListener('DOMContentLoaded',()=>{
  wireLogin();
  document.getElementById('menuBtn').onclick=toggleSidebar;
  document.getElementById('sidebarScrim').onclick=closeSidebar;
  document.getElementById('modalBackdrop').addEventListener('click',e=>{if(e.target.id==='modalBackdrop')closeModal()});
  document.getElementById('roleChip').onclick=()=>document.getElementById('roleMenu').classList.toggle('hidden');
  document.getElementById('roleMenu').addEventListener('click',e=>{const b=e.target.closest('[data-preview-role]');if(b)previewRole(b.dataset.previewRole)});
  document.getElementById('logoutBtn').onclick=logout;
  document.getElementById('quickSaleBtn').onclick=()=>navTo('pos');
  document.getElementById('notificationBtn').onclick=()=>navTo(can('tracking')?'tracking':'inventory');
  document.getElementById('tourBtn').onclick=startTour;
  document.getElementById('resetBtn').onclick=resetDemo;
  setTimeout(()=>document.getElementById('loader').classList.add('is-done'),3200);
  if(session)enterApp();else showLogin();
});

function wireLogin(){
  document.getElementById('loginForm').addEventListener('submit',e=>{e.preventDefault();const email=document.getElementById('loginEmail').value.trim().toLowerCase();const pw=document.getElementById('loginPassword').value;const u=db.users.find(x=>x.email===email);if(!u||pw!==DEMO_PASSWORD){toast('Demo login not recognised','bad');return}loginAs(u.role)});
  document.querySelectorAll('.role-login').forEach(b=>b.onclick=()=>loginAs(b.dataset.role));
}
function showLogin(){document.getElementById('loginScreen').classList.remove('hidden');document.getElementById('appShell').classList.add('hidden')}
function loginAs(r){session={role:r,loginAt:new Date().toISOString()};saveSession();enterApp();toast(`Logged in as ${roleConfig[r].label}`)}
function enterApp(){document.getElementById('loginScreen').classList.add('hidden');document.getElementById('appShell').classList.remove('hidden');currentView=can(currentView)?currentView:'dashboard';renderNav();updateUserUI();render()}
function logout(){sessionStorage.removeItem(SESSION_KEY);session=null;document.getElementById('roleMenu').classList.add('hidden');showLogin();toast('Logged out of demo')}
function previewRole(r){session.role=r;saveSession();document.getElementById('roleMenu').classList.add('hidden');if(!can(currentView))currentView='dashboard';renderNav();updateUserUI();render();toast(`Previewing ${roleConfig[r].label}`)}
function updateUserUI(){const r=role();document.getElementById('avatar').textContent=r.initials;document.getElementById('userName').textContent=r.name;document.getElementById('userRole').textContent=r.label;document.getElementById('quickSaleBtn').style.display=can('pos')?'':'none';document.getElementById('alertCount').textContent=lowVariants().length}
function renderNav(){const nav=document.getElementById('sideNav');nav.innerHTML='';navDefs.filter(([v])=>can(v)).forEach(([v,l,ico])=>{const b=document.createElement('button');b.className='nav-btn'+(v===currentView?' active':'');b.innerHTML=ico+`<span>${l}</span>`;b.onclick=()=>navTo(v);nav.appendChild(b)})}
function toggleSidebar(){const s=document.getElementById('sidebar');const sc=document.getElementById('sidebarScrim');s.classList.toggle('open');sc.classList.toggle('hidden',!s.classList.contains('open'))}
function closeSidebar(){document.getElementById('sidebar').classList.remove('open');document.getElementById('sidebarScrim').classList.add('hidden')}
function navTo(v){if(!can(v)){toast('This role does not have access to that module','warn');return}currentView=v;document.getElementById('pageTitle').textContent=label(v);renderNav();render();closeSidebar();window.scrollTo({top:0,behavior:'smooth'})}
function label(v){return Object.fromEntries(navDefs.map(([a,b])=>[a,b]))[v]||v}
function render(){const f={dashboard:dashboardView,pos:posView,inventory:inventoryView,customers:customersView,suppliers:suppliersView,purchasing:purchasingView,receipts:receiptsView,invoices:invoicesView,expenses:expensesView,tracking:trackingView,reports:reportsView,settings:settingsView}[currentView]||dashboardView;document.getElementById('content').innerHTML=f();updateUserUI()}

function stats(){
  const revenue=db.sales.reduce((a,s)=>a+s.total,0);
  const cogs=db.sales.reduce((a,s)=>a+s.items.reduce((x,i)=>x+i.cost*i.qty,0),0);
  const expenses=db.expenses.reduce((a,e)=>a+e.amount,0);
  const inventoryCost=db.products.reduce((a,p)=>a+p.variants.reduce((x,v)=>x+v.stock*p.cost,0),0);
  const inventoryRetail=db.products.reduce((a,p)=>a+p.variants.reduce((x,v)=>x+v.stock*p.price,0),0);
  const pending=db.invoices.filter(i=>i.status==='Pending').reduce((a,i)=>a+i.amount,0);
  return {revenue,cogs,expenses,gross:revenue-cogs,net:revenue-cogs-expenses,inventoryCost,inventoryRetail,pending,units:db.products.reduce((a,p)=>a+totalStock(p),0),low:lowVariants().length};
}
function dashboardView(){
  const s=stats(), lows=lowVariants();
  const hero=`<section class="hero-panel"><div><div class="hero-eyebrow">Retail Command Centre • ${role().label}</div><h1 class="hero-title">Run Sylvarts with <span>clarity, control & style.</span></h1><p class="hero-copy">A connected retail workflow from exact size-and-colour stock to sales, customers, purchasing, cash flow and management intelligence.</p><div class="hero-actions">${can('pos')?'<button class="btn btn-primary" onclick="navTo(\'pos\')">+ Start a Sale</button>':''}<button class="btn btn-secondary" onclick="navTo('inventory')">Review Inventory</button>${can('reports')?'<button class="btn btn-secondary" onclick="navTo(\'reports\')">Open Management Report</button>':''}</div></div><div class="hero-stat-stack"><div class="hero-mini-stat"><span>Stock at retail</span><strong>${money(s.inventoryRetail)}</strong></div><div class="hero-mini-stat"><span>Variant reorder alerts</span><strong>${s.low}</strong></div><div class="hero-mini-stat"><span>Outstanding invoices</span><strong>${money(s.pending)}</strong></div></div></section>`;
  const kpis=`<div class="grid-kpis">${kpi('Sales recorded',money(s.revenue),'Demo turnover','↗')}${kpi('Gross profit',money(s.gross),'Before operating expenses','◇')}${kpi('Inventory units',s.units,`${s.low} variant alerts`,'▦',s.low?'warn':'')}${kpi('Estimated net',money(s.net),'After demo expenses','◎',s.net<0?'down':'')}</div>`;
  const alerts=lows.slice(0,5).map(({product:p,variant:v})=>`<div class="alert-item ${v.stock===0?'critical':'warning'}"><span class="alert-dot"></span><div><b>${p.name} • ${v.size} • ${v.color}</b><p>${v.stock===0?'Out of stock':`${v.stock} unit${v.stock===1?'':'s'} remaining`} • reorder at ${v.reorder}</p></div></div>`).join('')||'<div class="empty-state"><p>All stock variants are healthy.</p></div>';
  return hero+kpis+`<div class="dashboard-grid"><div class="card"><div class="card-head"><div><h3>Sales momentum</h3><p>Recent trading performance</p></div><span class="badge badge-info">Interactive demo</span></div>${chartHtml()}</div><div class="card"><div class="card-head"><div><h3>Management attention</h3><p>Items requiring action now</p></div>${can('tracking')?'<button class="btn btn-small btn-secondary" onclick="navTo(\'tracking\')">View all</button>':''}</div><div class="alert-list">${alerts}</div></div></div><div class="dashboard-grid"><div class="card"><div class="card-head"><div><h3>Recent transactions</h3><p>Latest sales completed</p></div>${can('receipts')?'<button class="btn btn-small btn-secondary" onclick="navTo(\'receipts\')">Receipts</button>':''}</div>${salesTable(db.sales.slice(0,5))}</div><div class="card"><div class="card-head"><div><h3>Operational activity</h3><p>Audit-style demo feed</p></div></div><div class="activity-list">${activityHtml(db.activity.slice(0,6))}</div></div></div>`;
}
function kpi(labelTxt,value,sub,icon,cls=''){return `<div class="kpi-card"><div class="kpi-top"><span class="kpi-label">${labelTxt}</span><span class="kpi-icon">${icon}</span></div><div class="kpi-value">${value}</div><span class="trend ${cls}">${sub}</span></div>`}
function chartHtml(){const max=Math.max(...db.daily,1);return `<div class="chart-wrap"><div class="chart-bars">${db.daily.map(v=>`<div class="chart-bar" style="height:${Math.max(8,v/max*100)}%" data-value="${money(v)}"></div>`).join('')}</div><div class="chart-axis">${['9','10','11','12','13','14','15','16','17','18','19','20'].map(x=>`<span>${x} Aug</span>`).join('')}</div></div>`}
function salesTable(rows){return `<div class="table-wrap"><table class="data-table"><thead><tr><th>Sale</th><th>Customer</th><th>Payment</th><th>Items</th><th>Total</th><th>Date</th></tr></thead><tbody>${rows.map(s=>`<tr><td><b>${s.id}</b></td><td>${escapeHtml(s.customer)}</td><td>${s.method}</td><td>${s.items.reduce((a,i)=>a+i.qty,0)}</td><td><b>${money(s.total)}</b></td><td>${fmtDate(s.date)}</td></tr>`).join('')}</tbody></table></div>`}
function activityHtml(rows){const ico={sale:'↗',stock:'!',invoice:'▤',purchase:'⇣',expense:'−',customer:'♡'};return rows.map(a=>`<div class="activity"><span class="activity-icon">${ico[a.type]||'•'}</span><div><b>${escapeHtml(a.title)}</b><p>${escapeHtml(a.detail)}</p></div><time>${escapeHtml(a.time)}</time></div>`).join('')}

function posView(){
  const cats=['All',...new Set(db.products.map(p=>p.category))];
  const products=db.products.filter(p=>(posCategory==='All'||p.category===posCategory)&&(p.name.toLowerCase().includes(posSearch.toLowerCase())||p.sku.toLowerCase().includes(posSearch.toLowerCase())));
  return `<div class="section-head"><div><h2>Point of Sale</h2><p>Sell exact fashion variants and update inventory instantly.</p></div><div class="toolbar"><input class="field" placeholder="Search products" value="${escapeHtml(posSearch)}" oninput="setPosSearch(this.value)"><select class="select" onchange="setPosCategory(this.value)">${cats.map(c=>`<option ${c===posCategory?'selected':''}>${c}</option>`).join('')}</select></div></div><div class="pos-layout"><div class="card"><div class="card-head"><div><h3>Product catalogue</h3><p>Tap a product to choose size and colour</p></div><span class="badge badge-info">${products.length} products</span></div><div class="pos-products">${products.map(posProductCard).join('')}</div></div><aside class="card pos-cart"><div class="card-head"><div><h3>Current sale</h3><p>${saleCart.length?`${saleCart.reduce((a,i)=>a+i.qty,0)} item(s)`:'Cart is empty'}</p></div><button class="btn btn-small btn-secondary" onclick="clearCart()">Clear</button></div><div id="cartBody">${cartHtml()}</div></aside></div>`;
}
function posProductCard(p){const s=totalStock(p);return `<button class="pos-product" onclick="openVariantPicker(${p.id})"><div class="product-visual">${p.emoji}</div><b>${escapeHtml(p.name)}</b><small>${p.category} • ${s} units</small><strong>${money(p.price)}</strong></button>`}
function setPosSearch(v){posSearch=v;render()}
function setPosCategory(v){posCategory=v;render()}
function openVariantPicker(productId){const p=productById(productId);if(!p)return;openModal(`<div class="modal-head"><div><h3>${p.emoji} ${escapeHtml(p.name)}</h3><div class="muted" style="font-size:.68rem;margin-top:3px">Choose the exact size and colour to sell</div></div><button class="close-btn" onclick="closeModal()">×</button></div><div class="modal-body"><div class="variant-board">${p.variants.map(v=>{const st=stockBadge(v);return `<button class="variant-card" ${v.stock<=0?'disabled':''} onclick="addToCart(${p.id},'${v.id}')"><div class="variant-card-head"><div><b>${v.size} • ${v.color}</b><small>${p.sku}-${v.id.toUpperCase()}</small></div><span class="badge ${st[1]}">${st[0]}</span></div><div class="variant-stock">${v.stock}</div><small>units available</small></button>`}).join('')}</div></div><div class="modal-foot"><button class="btn btn-secondary" onclick="closeModal()">Cancel</button></div>`)}
function addToCart(productId,variantId){const p=productById(productId),v=variantById(p,variantId);if(!p||!v||v.stock<=0)return;const row=saleCart.find(x=>x.productId===p.id&&x.variantId===v.id);if(row){if(row.qty>=v.stock){toast('No more stock available for that variant','warn');return}row.qty++}else saleCart.push({productId:p.id,variantId:v.id,qty:1});closeModal();render();toast(`${p.name} • ${v.size} added`)}
function cartItemDetail(r){const p=productById(r.productId),v=variantById(p,r.variantId);return {p,v}}
function cartHtml(){if(!saleCart.length)return `<div class="empty-state"><div class="empty-icon">🛍</div><h3>Ready for a customer</h3><p>Select a product, choose the exact size and colour, then complete payment.</p></div>`;const subtotal=saleCart.reduce((a,r)=>{const {p}=cartItemDetail(r);return a+p.price*r.qty},0);return `<div class="cart-list">${saleCart.map((r,i)=>{const {p,v}=cartItemDetail(r);return `<div class="cart-item"><div><b>${p.emoji} ${escapeHtml(p.name)}</b><small>${v.size} • ${v.color} • ${money(p.price)}</small></div><div class="qty-control"><button onclick="cartQty(${i},-1)">−</button><span>${r.qty}</span><button onclick="cartQty(${i},1)">+</button></div></div>`}).join('')}</div><div class="cart-total"><div class="summary-row"><span>Subtotal</span><strong>${money(subtotal)}</strong></div><label class="form-field" style="display:block;margin-top:9px"><label>Customer</label><select id="saleCustomer"><option value="">Walk-in Customer</option>${db.customers.map(c=>`<option value="${c.id}">${escapeHtml(c.name)}</option>`).join('')}</select></label><div class="form-grid" style="margin-top:9px"><div class="form-field"><label>Payment</label><select id="saleMethod"><option>Mobile Money</option><option>Cash</option><option>Card</option><option>Bank Transfer</option></select></div><div class="form-field"><label>Discount (UGX)</label><input id="saleDiscount" type="number" min="0" value="0"></div></div><div class="big-total"><span>Total due</span><strong>${money(subtotal)}</strong></div><div class="cart-actions"><button class="btn btn-primary" onclick="completeSale()">Complete Sale & Create Receipt</button><button class="btn btn-secondary" onclick="holdSale()">Hold Sale</button></div></div>`}
function cartQty(index,delta){const row=saleCart[index];if(!row)return;const {v}=cartItemDetail(row);row.qty+=delta;if(row.qty<=0)saleCart.splice(index,1);else if(row.qty>v.stock){row.qty=v.stock;toast('Maximum available stock reached','warn')}render()}
function clearCart(){saleCart=[];render()}
function holdSale(){if(!saleCart.length)return;toast('Sale held for demo — cart remains available')}
function completeSale(){if(!saleCart.length){toast('Add at least one item','warn');return}for(const r of saleCart){const {v}=cartItemDetail(r);if(!v||v.stock<r.qty){toast('Stock changed — review the cart','bad');return}}const customerId=Number(document.getElementById('saleCustomer')?.value||0)||null;const customer=customerId?customerById(customerId)?.name:'Walk-in Customer';const method=document.getElementById('saleMethod')?.value||'Cash';const discount=Math.max(0,Number(document.getElementById('saleDiscount')?.value||0));const items=saleCart.map(r=>{const {p,v}=cartItemDetail(r);v.stock-=r.qty;return {productId:p.id,variantId:v.id,name:p.name,variant:`${v.size} • ${v.color}`,qty:r.qty,price:p.price,cost:p.cost}});const subtotal=items.reduce((a,i)=>a+i.price*i.qty,0);const total=Math.max(0,subtotal-discount);const num=1049+db.sales.length;const sale={id:`S-${num}`,receipt:`RCT-${num}`,date:new Date().toISOString(),customerId,customer,method,discount,items,total};db.sales.unshift(sale);db.daily[db.daily.length-1]+=total;addActivity('sale',`Sale ${sale.id} completed`,`${customer} • ${method} • ${money(total)}`);saveDb();saleCart=[];updateUserUI();showReceipt(sale.id);toast('Sale completed and inventory updated')}

function inventoryView(){return `<div class="section-head"><div><h2>Inventory & Variants</h2><p>Control products by exact size, colour, stock and reorder level.</p></div><div class="toolbar"><input class="field" id="stockSearch" placeholder="Search product or SKU" oninput="filterInventory()"><select class="select" id="stockFilter" onchange="filterInventory()"><option value="all">All stock</option><option value="low">Needs reorder</option><option value="out">Out of stock</option></select>${session.role!=='sales'?'<button class="btn btn-secondary" onclick="exportInventory()">Export CSV</button><button class="btn btn-primary" onclick="openProduct()">+ Add Product</button>':''}</div></div><div class="card"><div id="inventoryTable">${inventoryTable(db.products)}</div></div>`}
function inventoryTable(products){return `<div class="table-wrap"><table class="data-table"><thead><tr><th>Product</th><th>SKU</th><th>Category</th><th>Variants</th>${session.role!=='sales'?'<th>Cost</th>':''}<th>Price</th><th>Total Stock</th><th>Status</th><th></th></tr></thead><tbody>${products.map(p=>{const st=productStockState(p);return `<tr><td><div class="product-cell"><span class="product-thumb">${p.emoji}</span><div><b>${escapeHtml(p.name)}</b><small>${p.variants.length} configured variants</small></div></div></td><td>${p.sku}</td><td>${p.category}</td><td><div class="variant-pills">${p.variants.slice(0,4).map(v=>`<span class="variant-pill">${v.size}/${v.color}: ${v.stock}</span>`).join('')}${p.variants.length>4?`<span class="variant-pill">+${p.variants.length-4}</span>`:''}</div></td>${session.role!=='sales'?`<td>${money(p.cost)}</td>`:''}<td><b>${money(p.price)}</b></td><td>${totalStock(p)}</td><td><span class="badge ${st[1]}">${st[0]}</span></td><td><button class="btn btn-small btn-secondary" onclick="viewProduct(${p.id})">${session.role==='sales'?'View':'Manage'}</button></td></tr>`}).join('')}</tbody></table></div>`}
function filterInventory(){const q=(document.getElementById('stockSearch')?.value||'').toLowerCase(),f=document.getElementById('stockFilter')?.value||'all';const rows=db.products.filter(p=>(p.name.toLowerCase().includes(q)||p.sku.toLowerCase().includes(q)||p.category.toLowerCase().includes(q))&&(f==='all'||(f==='low'&&p.variants.some(v=>v.stock<=v.reorder))||(f==='out'&&p.variants.some(v=>v.stock===0))));document.getElementById('inventoryTable').innerHTML=inventoryTable(rows)}
function viewProduct(id){const p=productById(id);if(!p)return;const editable=session.role!=='sales';openModal(`<div class="modal-head"><div><h3>${p.emoji} ${escapeHtml(p.name)}</h3><div class="muted" style="font-size:.67rem;margin-top:3px">${p.sku} • ${p.category}</div></div><button class="close-btn" onclick="closeModal()">×</button></div><div class="modal-body"><div class="grid-kpis" style="grid-template-columns:repeat(3,1fr);margin-bottom:15px">${kpi('Total stock',totalStock(p),'Across all variants','▦')}${kpi('Retail value',money(totalStock(p)*p.price),'Current stock','◇')}${kpi('Margin / unit',money(p.price-p.cost),'Before expenses','↗')}</div><div class="variant-board">${p.variants.map(v=>variantManageCard(p,v,editable)).join('')}</div></div><div class="modal-foot">${editable?`<button class="btn btn-secondary" onclick="openProduct(${p.id})">Edit Product</button><button class="btn btn-primary" onclick="openAddVariant(${p.id})">+ Add Variant</button>`:''}<button class="btn btn-secondary" onclick="closeModal()">Close</button></div>`,true)}
function variantManageCard(p,v,editable){const st=stockBadge(v),pct=Math.min(100,v.stock/Math.max(v.reorder*2,1)*100);return `<div class="variant-card"><div class="variant-card-head"><div><b>${v.size} • ${v.color}</b><small>${p.sku}-${v.id.toUpperCase()}</small></div><span class="badge ${st[1]}">${st[0]}</span></div><div class="variant-stock">${v.stock}</div><small>reorder at ${v.reorder}</small><div class="stock-meter ${v.stock===0?'out':v.stock<=v.reorder?'low':''}" style="margin-top:8px"><span style="width:${pct}%"></span></div>${editable?`<div class="table-actions" style="margin-top:9px"><button class="btn btn-small btn-secondary" onclick="adjustStock(${p.id},'${v.id}',1)">+1</button><button class="btn btn-small btn-secondary" onclick="adjustStock(${p.id},'${v.id}',-1)">−1</button>${v.stock<=v.reorder?`<button class="btn btn-small btn-soft" onclick="createPOFromVariant(${p.id},'${v.id}')">Reorder</button>`:''}</div>`:''}</div>`}
function adjustStock(pid,vid,delta){const p=productById(pid),v=variantById(p,vid);if(!v)return;v.stock=Math.max(0,v.stock+delta);addActivity('stock',`${p.name} stock adjusted`,`${v.size} • ${v.color}: ${delta>0?'+':''}${delta}`);saveDb();viewProduct(pid);updateUserUI()}
function openProduct(id){const p=id?productById(id):null;openModal(`<div class="modal-head"><h3>${p?'Edit':'Add'} Product</h3><button class="close-btn" onclick="closeModal()">×</button></div><div class="modal-body"><div class="form-grid"><div class="form-field"><label>Product name</label><input id="pName" value="${escapeHtml(p?.name||'')}"></div><div class="form-field"><label>SKU</label><input id="pSku" value="${escapeHtml(p?.sku||'SFC-NEW-001')}"></div><div class="form-field"><label>Category</label><input id="pCategory" value="${escapeHtml(p?.category||'Heels')}"></div><div class="form-field"><label>Product icon / emoji</label><input id="pEmoji" value="${escapeHtml(p?.emoji||'👠')}"></div><div class="form-field"><label>Unit cost (UGX)</label><input id="pCost" type="number" value="${p?.cost||0}"></div><div class="form-field"><label>Selling price (UGX)</label><input id="pPrice" type="number" value="${p?.price||0}"></div></div>${!p?'<p class="muted" style="font-size:.7rem;margin-top:13px">A default variant will be created. You can add sizes and colours immediately after saving.</p>':''}</div><div class="modal-foot"><button class="btn btn-secondary" onclick="closeModal()">Cancel</button><button class="btn btn-primary" onclick="saveProduct(${p?.id||0})">Save Product</button></div>`)}
function saveProduct(id){const data={name:document.getElementById('pName').value.trim(),sku:document.getElementById('pSku').value.trim(),category:document.getElementById('pCategory').value.trim(),emoji:document.getElementById('pEmoji').value.trim()||'🛍',cost:Number(document.getElementById('pCost').value||0),price:Number(document.getElementById('pPrice').value||0)};if(!data.name||!data.sku){toast('Product name and SKU are required','warn');return}if(id){Object.assign(productById(id),data)}else{const next=Math.max(0,...db.products.map(p=>p.id))+1;db.products.push({...data,id:next,variants:[{id:`${next}a`,size:'One size',color:'Default',stock:0,reorder:2}]});id=next}saveDb();closeModal();render();toast('Product saved');setTimeout(()=>viewProduct(id),120)}
function openAddVariant(pid){const p=productById(pid);openModal(`<div class="modal-head"><h3>Add Variant • ${escapeHtml(p.name)}</h3><button class="close-btn" onclick="closeModal()">×</button></div><div class="modal-body"><div class="form-grid"><div class="form-field"><label>Size</label><input id="vSize" placeholder="e.g. 38 / M / One size"></div><div class="form-field"><label>Colour</label><input id="vColor" placeholder="e.g. Pink"></div><div class="form-field"><label>Opening stock</label><input id="vStock" type="number" min="0" value="0"></div><div class="form-field"><label>Reorder level</label><input id="vReorder" type="number" min="0" value="2"></div></div></div><div class="modal-foot"><button class="btn btn-secondary" onclick="viewProduct(${pid})">Back</button><button class="btn btn-primary" onclick="saveVariant(${pid})">Add Variant</button></div>`)}
function saveVariant(pid){const p=productById(pid);const size=document.getElementById('vSize').value.trim(),color=document.getElementById('vColor').value.trim();if(!size||!color){toast('Size and colour are required','warn');return}p.variants.push({id:`${pid}${String.fromCharCode(97+p.variants.length)}`,size,color,stock:Number(document.getElementById('vStock').value||0),reorder:Number(document.getElementById('vReorder').value||0)});saveDb();toast('Variant added');viewProduct(pid)}
function exportInventory(){const rows=[['SKU','Product','Category','Size','Colour','Stock','Reorder','Cost','Price']];db.products.forEach(p=>p.variants.forEach(v=>rows.push([p.sku,p.name,p.category,v.size,v.color,v.stock,v.reorder,p.cost,p.price])));downloadText('sylvarts-inventory.csv',rows.map(r=>r.map(x=>`"${String(x).replace(/"/g,'""')}"`).join(',')).join('\n'),'text/csv')}

function customersView(){return `<div class="section-head"><div><h2>Customers & Loyalty</h2><p>Customer history, spend, segments and follow-up context.</p></div><button class="btn btn-primary" onclick="openCustomer()">+ Add Customer</button></div><div class="profile-grid">${db.customers.map(customerCard).join('')}</div>`}
function customerSpend(id){return db.sales.filter(s=>s.customerId===id).reduce((a,s)=>a+s.total,0)}
function customerCard(c){const count=db.sales.filter(s=>s.customerId===c.id).length;return `<div class="profile-card"><div class="profile-head"><div class="profile-avatar">${c.name.slice(0,2).toUpperCase()}</div><div><h4>${escapeHtml(c.name)}</h4><p>${escapeHtml(c.segment)} • ${escapeHtml(c.phone)}</p></div></div><div class="profile-metrics"><div><span>Total spend</span><strong>${money(customerSpend(c.id))}</strong></div><div><span>Purchases</span><strong>${count}</strong></div></div><button class="btn btn-small btn-secondary" style="margin-top:11px;width:100%" onclick="viewCustomer(${c.id})">Open Customer Profile</button></div>`}
function openCustomer(){openModal(`<div class="modal-head"><h3>Add Customer</h3><button class="close-btn" onclick="closeModal()">×</button></div><div class="modal-body"><div class="form-grid"><div class="form-field"><label>Name</label><input id="cName"></div><div class="form-field"><label>Phone</label><input id="cPhone" value="+256 "></div><div class="form-field"><label>Email</label><input id="cEmail" type="email"></div><div class="form-field"><label>Segment</label><select id="cSegment"><option>Regular</option><option>VIP</option><option>Wholesale</option></select></div></div></div><div class="modal-foot"><button class="btn btn-secondary" onclick="closeModal()">Cancel</button><button class="btn btn-primary" onclick="saveCustomer()">Save Customer</button></div>`)}
function saveCustomer(){const name=document.getElementById('cName').value.trim();if(!name){toast('Customer name is required','warn');return}const id=Math.max(0,...db.customers.map(c=>c.id))+1;db.customers.push({id,name,phone:document.getElementById('cPhone').value.trim(),email:document.getElementById('cEmail').value.trim(),segment:document.getElementById('cSegment').value,joined:new Date().toISOString().slice(0,10)});addActivity('customer','New customer added',name);saveDb();closeModal();render();toast('Customer added')}
function viewCustomer(id){const c=customerById(id),sales=db.sales.filter(s=>s.customerId===id);openModal(`<div class="modal-head"><div><h3>${escapeHtml(c.name)}</h3><div class="muted" style="font-size:.66rem;margin-top:3px">${escapeHtml(c.segment)} • Customer since ${fmtDate(c.joined)}</div></div><button class="close-btn" onclick="closeModal()">×</button></div><div class="modal-body"><div class="grid-kpis" style="grid-template-columns:repeat(3,1fr);margin-bottom:15px">${kpi('Lifetime spend',money(customerSpend(id)),'Recorded sales','↗')}${kpi('Purchases',sales.length,'Transactions','▤')}${kpi('Contact',c.phone||'—','Primary phone','☎')}</div><h4 style="margin:0 0 9px">Purchase history</h4>${sales.length?salesTable(sales):'<div class="empty-state"><p>No recorded purchases yet.</p></div>'}</div><div class="modal-foot"><button class="btn btn-secondary" onclick="closeModal()">Close</button>${can('invoices')?`<button class="btn btn-primary" onclick="closeModal();openInvoice(${id})">Create Invoice</button>`:''}</div>`,true)}

function suppliersView(){return `<div class="section-head"><div><h2>Suppliers</h2><p>Supply partners, lead times and purchasing contacts.</p></div><button class="btn btn-primary" onclick="openSupplier()">+ Add Supplier</button></div><div class="profile-grid">${db.suppliers.map(supplierCard).join('')}</div>`}
function supplierCard(s){const po=db.purchaseOrders.filter(p=>p.supplierId===s.id);return `<div class="profile-card"><div class="profile-head"><div class="profile-avatar">${s.name.slice(0,2).toUpperCase()}</div><div><h4>${escapeHtml(s.name)}</h4><p>${escapeHtml(s.contact)} • ${s.lead} day lead</p></div></div><p style="margin-top:10px">${escapeHtml(s.categories)}</p><div class="profile-metrics"><div><span>Purchase orders</span><strong>${po.length}</strong></div><div><span>Open value</span><strong>${money(po.filter(x=>x.status!=='Received').reduce((a,x)=>a+x.total,0))}</strong></div></div><button class="btn btn-small btn-secondary" style="width:100%;margin-top:11px" onclick="viewSupplier(${s.id})">Supplier Details</button></div>`}
function openSupplier(){openModal(`<div class="modal-head"><h3>Add Supplier</h3><button class="close-btn" onclick="closeModal()">×</button></div><div class="modal-body"><div class="form-grid"><div class="form-field"><label>Supplier name</label><input id="sName"></div><div class="form-field"><label>Contact person</label><input id="sContact"></div><div class="form-field"><label>Phone</label><input id="sPhone" value="+256 "></div><div class="form-field"><label>Email</label><input id="sEmail"></div><div class="form-field"><label>Lead time (days)</label><input id="sLead" type="number" value="7"></div><div class="form-field"><label>Categories</label><input id="sCats" placeholder="Heels, Bags..."></div></div></div><div class="modal-foot"><button class="btn btn-secondary" onclick="closeModal()">Cancel</button><button class="btn btn-primary" onclick="saveSupplier()">Save Supplier</button></div>`)}
function saveSupplier(){const name=document.getElementById('sName').value.trim();if(!name){toast('Supplier name is required','warn');return}const id=Math.max(0,...db.suppliers.map(s=>s.id))+1;db.suppliers.push({id,name,contact:document.getElementById('sContact').value.trim(),phone:document.getElementById('sPhone').value.trim(),email:document.getElementById('sEmail').value.trim(),lead:Number(document.getElementById('sLead').value||7),categories:document.getElementById('sCats').value.trim()});saveDb();closeModal();render();toast('Supplier added')}
function viewSupplier(id){const s=supplierById(id),orders=db.purchaseOrders.filter(p=>p.supplierId===id);openModal(`<div class="modal-head"><div><h3>${escapeHtml(s.name)}</h3><div class="muted" style="font-size:.66rem;margin-top:3px">${escapeHtml(s.contact)} • ${escapeHtml(s.phone)}</div></div><button class="close-btn" onclick="closeModal()">×</button></div><div class="modal-body"><div class="summary-list"><div class="summary-row"><span>Email</span><strong>${escapeHtml(s.email)}</strong></div><div class="summary-row"><span>Lead time</span><strong>${s.lead} days</strong></div><div class="summary-row"><span>Supplies</span><strong>${escapeHtml(s.categories)}</strong></div></div><h4>Purchase history</h4>${orders.length?poTable(orders):'<div class="empty-state"><p>No purchase orders yet.</p></div>'}</div><div class="modal-foot"><button class="btn btn-secondary" onclick="closeModal()">Close</button></div>`,true)}
function purchasingView(){const low=lowVariants();return `<div class="section-head"><div><h2>Purchasing & Reorder Centre</h2><p>Turn low-stock intelligence into supplier orders and receive stock back into inventory.</p></div><button class="btn btn-primary" onclick="openPurchaseOrder()">+ New Purchase Order</button></div><div class="dashboard-grid"><div class="card"><div class="card-head"><div><h3>Recommended reorders</h3><p>Variant-level recommendations based on current thresholds</p></div><span class="badge badge-low">${low.length} alerts</span></div><div class="alert-list">${low.map(({product:p,variant:v})=>`<div class="alert-item ${v.stock===0?'critical':'warning'}"><span class="alert-dot"></span><div style="flex:1"><b>${p.name} • ${v.size} • ${v.color}</b><p>${v.stock} available • reorder level ${v.reorder} • suggested order ${Math.max(4,v.reorder*3-v.stock)} units</p></div><button class="btn btn-small btn-soft" onclick="createPOFromVariant(${p.id},'${v.id}')">Create PO</button></div>`).join('')||'<div class="empty-state"><p>No reorder recommendations.</p></div>'}</div></div><div class="card"><div class="card-head"><div><h3>Purchasing summary</h3><p>Current pipeline</p></div></div><div class="summary-list"><div class="summary-row"><span>Open POs</span><strong>${db.purchaseOrders.filter(p=>p.status!=='Received').length}</strong></div><div class="summary-row"><span>Open order value</span><strong>${money(db.purchaseOrders.filter(p=>p.status!=='Received').reduce((a,p)=>a+p.total,0))}</strong></div><div class="summary-row"><span>Received orders</span><strong>${db.purchaseOrders.filter(p=>p.status==='Received').length}</strong></div><div class="summary-row"><span>Suppliers</span><strong>${db.suppliers.length}</strong></div></div></div></div><div class="card" style="margin-top:15px"><div class="card-head"><div><h3>Purchase orders</h3><p>Order, expected delivery and receiving status</p></div></div>${poTable(db.purchaseOrders)}</div>`}
function poTable(rows){return `<div class="table-wrap"><table class="data-table"><thead><tr><th>PO</th><th>Supplier</th><th>Items</th><th>Value</th><th>ETA</th><th>Status</th><th></th></tr></thead><tbody>${rows.map(p=>`<tr><td><b>${p.id}</b></td><td>${escapeHtml(p.supplier)}</td><td>${p.items.reduce((a,i)=>a+i.qty,0)}</td><td>${money(p.total)}</td><td>${fmtDate(p.eta)}</td><td><span class="badge ${p.status==='Received'?'badge-paid':'badge-pending'}">${p.status}</span></td><td>${p.status!=='Received'?`<button class="btn btn-small btn-primary" onclick="receivePO('${p.id}')">Receive</button>`:'<span class="badge badge-ok">Stock updated</span>'}</td></tr>`).join('')}</tbody></table></div>`}
function createPOFromVariant(pid,vid){const p=productById(pid),v=variantById(p,vid);openPurchaseOrder(pid,vid,Math.max(4,v.reorder*3-v.stock))}
function openPurchaseOrder(pid='',vid='',qty=6){const p=pid?productById(pid):null;openModal(`<div class="modal-head"><h3>Create Purchase Order</h3><button class="close-btn" onclick="closeModal()">×</button></div><div class="modal-body"><div class="form-grid"><div class="form-field"><label>Supplier</label><select id="poSupplier">${db.suppliers.map(s=>`<option value="${s.id}">${escapeHtml(s.name)}</option>`).join('')}</select></div><div class="form-field"><label>Product</label><select id="poProduct" onchange="refreshPoVariants(this.value)">${db.products.map(x=>`<option value="${x.id}" ${p?.id===x.id?'selected':''}>${escapeHtml(x.name)}</option>`).join('')}</select></div><div class="form-field"><label>Variant</label><select id="poVariant">${(p||db.products[0]).variants.map(v=>`<option value="${v.id}" ${vid===v.id?'selected':''}>${v.size} • ${v.color}</option>`).join('')}</select></div><div class="form-field"><label>Quantity</label><input id="poQty" type="number" min="1" value="${qty}"></div><div class="form-field"><label>Expected delivery</label><input id="poEta" type="date" value="${new Date(Date.now()+6*86400000).toISOString().slice(0,10)}"></div></div></div><div class="modal-foot"><button class="btn btn-secondary" onclick="closeModal()">Cancel</button><button class="btn btn-primary" onclick="savePO()">Create Purchase Order</button></div>`)}
function refreshPoVariants(pid){const p=productById(pid);document.getElementById('poVariant').innerHTML=p.variants.map(v=>`<option value="${v.id}">${v.size} • ${v.color}</option>`).join('')}
function savePO(){const supplier=supplierById(document.getElementById('poSupplier').value),p=productById(document.getElementById('poProduct').value),v=variantById(p,document.getElementById('poVariant').value),qty=Math.max(1,Number(document.getElementById('poQty').value||1));const n=13+db.purchaseOrders.length;const po={id:`PO-2026-${String(n).padStart(3,'0')}`,supplierId:supplier.id,supplier:supplier.name,date:new Date().toISOString().slice(0,10),status:'Ordered',eta:document.getElementById('poEta').value,items:[{productId:p.id,variantId:v.id,description:`${p.name} • ${v.size} • ${v.color}`,qty,cost:p.cost}],total:qty*p.cost};db.purchaseOrders.unshift(po);addActivity('purchase',`${po.id} created`,`${supplier.name} • ${qty} units • ${money(po.total)}`);saveDb();closeModal();render();toast('Purchase order created')}
function receivePO(id){const po=db.purchaseOrders.find(p=>p.id===id);if(!po||po.status==='Received')return;po.items.forEach(i=>{const p=productById(i.productId),v=variantById(p,i.variantId);if(v)v.stock+=i.qty});po.status='Received';addActivity('purchase',`${po.id} received`,'Inventory quantities updated automatically');saveDb();render();updateUserUI();toast('Purchase order received — stock updated')}

function receiptsView(){return `<div class="section-head"><div><h2>Receipts</h2><p>Branded sales documents generated from completed transactions.</p></div></div><div class="card">${salesTableWithActions(db.sales)}</div>`}
function salesTableWithActions(rows){return `<div class="table-wrap"><table class="data-table"><thead><tr><th>Receipt</th><th>Sale</th><th>Customer</th><th>Payment</th><th>Total</th><th>Date</th><th></th></tr></thead><tbody>${rows.map(s=>`<tr><td><b>${s.receipt}</b></td><td>${s.id}</td><td>${escapeHtml(s.customer)}</td><td>${s.method}</td><td><b>${money(s.total)}</b></td><td>${fmtDate(s.date)}</td><td><button class="btn btn-small btn-secondary" onclick="showReceipt('${s.id}')">Preview</button></td></tr>`).join('')}</tbody></table></div>`}
function showReceipt(id){const s=db.sales.find(x=>x.id===id);if(!s)return;openModal(`<div class="modal-head"><h3>Receipt Preview • ${s.receipt}</h3><button class="close-btn" onclick="closeModal()">×</button></div><div class="modal-body doc-preview">${documentHtml('RECEIPT',s.receipt,s.date,s.customer,s.items.map(i=>({description:`${i.name} • ${i.variant}`,qty:i.qty,price:i.price})),s.total,`Payment: ${s.method}${s.discount?` • Discount: ${money(s.discount)}`:''}`)}</div><div class="modal-foot"><button class="btn btn-secondary" onclick="closeModal()">Close</button><button class="btn btn-dark" onclick="window.print()">Print / Save PDF</button></div>`,true)}
function invoicesView(){return `<div class="section-head"><div><h2>Invoices</h2><p>Create, track, mark paid and print branded customer invoices.</p></div><button class="btn btn-primary" onclick="openInvoice()">+ Create Invoice</button></div><div class="grid-kpis" style="margin-bottom:15px">${kpi('Outstanding',money(db.invoices.filter(i=>i.status==='Pending').reduce((a,i)=>a+i.amount,0)),'Pending collection','▤')}${kpi('Paid invoices',db.invoices.filter(i=>i.status==='Paid').length,'Completed','✓')}${kpi('Drafts',db.invoices.filter(i=>i.status==='Draft').length,'Not yet issued','◇')}${kpi('Invoice value',money(db.invoices.reduce((a,i)=>a+i.amount,0)),'All demo invoices','↗')}</div><div class="card">${invoiceTable(db.invoices)}</div>`}
function invoiceTable(rows){return `<div class="table-wrap"><table class="data-table"><thead><tr><th>Invoice</th><th>Customer</th><th>Amount</th><th>Issued</th><th>Due</th><th>Status</th><th></th></tr></thead><tbody>${rows.map(i=>`<tr><td><b>${i.id}</b></td><td>${escapeHtml(i.customer)}</td><td><b>${money(i.amount)}</b></td><td>${fmtDate(i.date)}</td><td>${fmtDate(i.due)}</td><td><span class="badge ${i.status==='Paid'?'badge-paid':i.status==='Pending'?'badge-pending':'badge-draft'}">${i.status}</span></td><td><div class="table-actions"><button class="btn btn-small btn-secondary" onclick="showInvoice('${i.id}')">Preview</button>${i.status==='Pending'?`<button class="btn btn-small btn-primary" onclick="markInvoicePaid('${i.id}')">Mark Paid</button>`:''}</div></td></tr>`).join('')}</tbody></table></div>`}
function openInvoice(customerId=''){invoiceCart=[];const customerOptions=db.customers.map(c=>`<option value="${c.id}" ${Number(customerId)===c.id?'selected':''}>${escapeHtml(c.name)}</option>`).join('');openModal(`<div class="modal-head"><h3>Create Invoice</h3><button class="close-btn" onclick="closeModal()">×</button></div><div class="modal-body"><div class="form-grid"><div class="form-field"><label>Customer</label><select id="invCustomer"><option value="">Private Client</option>${customerOptions}</select></div><div class="form-field"><label>Due date</label><input id="invDue" type="date" value="${new Date(Date.now()+7*86400000).toISOString().slice(0,10)}"></div></div><div style="margin-top:16px;padding-top:15px;border-top:1px solid var(--line)"><div class="form-grid"><div class="form-field"><label>Product / description</label><select id="invProduct"><option value="custom">Custom line item</option>${db.products.map(p=>`<option value="${p.id}">${escapeHtml(p.name)} • ${money(p.price)}</option>`).join('')}</select></div><div class="form-field"><label>Quantity</label><input id="invQty" type="number" min="1" value="1"></div><div class="form-field full"><label>Custom description (optional)</label><input id="invDesc" placeholder="e.g. Mixed fashion stock order"></div></div><button class="btn btn-secondary" style="margin-top:10px" onclick="addInvoiceLine()">+ Add Line</button><div id="invoiceCartBox" style="margin-top:12px">${invoiceCartHtml()}</div></div></div><div class="modal-foot"><button class="btn btn-secondary" onclick="closeModal()">Cancel</button><button class="btn btn-secondary" onclick="saveInvoice('Draft')">Save Draft</button><button class="btn btn-primary" onclick="saveInvoice('Pending')">Issue Invoice</button></div>`,true)}
function addInvoiceLine(){const val=document.getElementById('invProduct').value,qty=Math.max(1,Number(document.getElementById('invQty').value||1)),custom=document.getElementById('invDesc').value.trim();if(val==='custom'){if(!custom){toast('Enter a custom description','warn');return}invoiceCart.push({description:custom,qty,price:0})}else{const p=productById(val);invoiceCart.push({description:custom||p.name,qty,price:p.price})}document.getElementById('invoiceCartBox').innerHTML=invoiceCartHtml()}
function invoiceCartHtml(){if(!invoiceCart.length)return '<div class="muted" style="font-size:.7rem">No invoice lines yet.</div>';return `<div class="table-wrap"><table class="data-table" style="min-width:0"><thead><tr><th>Description</th><th>Qty</th><th>Price</th><th>Total</th></tr></thead><tbody>${invoiceCart.map(i=>`<tr><td>${escapeHtml(i.description)}</td><td>${i.qty}</td><td>${money(i.price)}</td><td>${money(i.qty*i.price)}</td></tr>`).join('')}</tbody></table></div><div class="summary-row"><span>Invoice total</span><strong>${money(invoiceCart.reduce((a,i)=>a+i.qty*i.price,0))}</strong></div>`}
function saveInvoice(status){if(!invoiceCart.length){toast('Add at least one invoice line','warn');return}const cid=Number(document.getElementById('invCustomer').value||0)||null,c=cid?customerById(cid):null;const n=19+db.invoices.length;const inv={id:`INV-2026-${String(n).padStart(3,'0')}`,date:new Date().toISOString().slice(0,10),customerId:cid,customer:c?.name||'Private Client',due:document.getElementById('invDue').value,status,items:clone(invoiceCart),amount:invoiceCart.reduce((a,i)=>a+i.qty*i.price,0)};db.invoices.unshift(inv);addActivity('invoice',`${inv.id} ${status==='Draft'?'saved':'issued'}`,`${inv.customer} • ${money(inv.amount)}`);saveDb();closeModal();render();toast(`Invoice ${status==='Draft'?'saved':'issued'}`)}
function showInvoice(id){const i=db.invoices.find(x=>x.id===id);if(!i)return;openModal(`<div class="modal-head"><h3>Invoice Preview • ${i.id}</h3><button class="close-btn" onclick="closeModal()">×</button></div><div class="modal-body doc-preview">${documentHtml('INVOICE',i.id,i.date,i.customer,i.items,i.amount,`Due: ${fmtDate(i.due)} • Status: ${i.status}`)}</div><div class="modal-foot"><button class="btn btn-secondary" onclick="closeModal()">Close</button>${i.status==='Pending'?`<button class="btn btn-primary" onclick="markInvoicePaid('${i.id}')">Mark Paid</button>`:''}<button class="btn btn-dark" onclick="window.print()">Print / Save PDF</button></div>`,true)}
function markInvoicePaid(id){const i=db.invoices.find(x=>x.id===id);if(!i)return;i.status='Paid';addActivity('invoice',`${i.id} marked paid`,`${i.customer} • ${money(i.amount)}`);saveDb();closeModal();render();toast('Invoice marked paid')}
function documentHtml(type,number,date,customer,items,total,meta){return `<div class="document"><div class="doc-head"><div><div class="doc-logo"><img src="Slyvarts-logo.png" alt="Sylvarts logo"></div><div style="margin-top:8px"><b>Sylvarts Fashion Collection</b><div class="muted" style="font-size:.65rem;margin-top:3px">Premium fashion retail • Kampala, Uganda</div></div></div><div class="doc-title"><h2>${type}</h2><p>${number}</p></div></div><div class="doc-meta"><div><span>Billed / sold to</span><b>${escapeHtml(customer)}</b></div><div><span>Date</span><b>${fmtDate(date)}</b></div></div><table class="doc-table"><thead><tr><th>Description</th><th>Qty</th><th>Unit price</th><th>Total</th></tr></thead><tbody>${items.map(i=>`<tr><td>${escapeHtml(i.description)}</td><td>${i.qty}</td><td>${money(i.price)}</td><td>${money(i.price*i.qty)}</td></tr>`).join('')}</tbody></table><div class="doc-total"><div class="summary-row"><span>Total</span><strong>${money(total)}</strong></div></div><div class="doc-footer">${escapeHtml(meta)}<br><br>Thank you for choosing Sylvarts Fashion Collection.</div></div>`}

function expensesView(){const total=db.expenses.reduce((a,e)=>a+e.amount,0);return `<div class="section-head"><div><h2>Expenses & Cash Control</h2><p>Track operating costs so management reports show more than sales alone.</p></div><button class="btn btn-primary" onclick="openExpense()">+ Record Expense</button></div><div class="grid-kpis" style="margin-bottom:15px">${kpi('Operating expenses',money(total),'Demo period','−')}${kpi('Largest category',topExpenseCategory().name,money(topExpenseCategory().amount),'▤')}${kpi('Transactions',db.expenses.length,'Expense entries','◇')}${kpi('Avg. expense',money(total/Math.max(db.expenses.length,1)),'Per entry','◎')}</div><div class="card">${expenseTable(db.expenses)}</div>`}
function topExpenseCategory(){const m={};db.expenses.forEach(e=>m[e.category]=(m[e.category]||0)+e.amount);const arr=Object.entries(m).sort((a,b)=>b[1]-a[1]);return {name:arr[0]?.[0]||'—',amount:arr[0]?.[1]||0}}
function expenseTable(rows){return `<div class="table-wrap"><table class="data-table"><thead><tr><th>Expense</th><th>Date</th><th>Category</th><th>Description</th><th>Method</th><th>Amount</th></tr></thead><tbody>${rows.map(e=>`<tr><td><b>${e.id}</b></td><td>${fmtDate(e.date)}</td><td>${e.category}</td><td>${escapeHtml(e.description)}</td><td>${e.method}</td><td><b>${money(e.amount)}</b></td></tr>`).join('')}</tbody></table></div>`}
function openExpense(){openModal(`<div class="modal-head"><h3>Record Expense</h3><button class="close-btn" onclick="closeModal()">×</button></div><div class="modal-body"><div class="form-grid"><div class="form-field"><label>Category</label><select id="eCat"><option>Packaging</option><option>Transport</option><option>Marketing</option><option>Utilities</option><option>Rent</option><option>Wages</option><option>Other</option></select></div><div class="form-field"><label>Amount (UGX)</label><input id="eAmount" type="number" min="0"></div><div class="form-field"><label>Payment method</label><select id="eMethod"><option>Mobile Money</option><option>Cash</option><option>Bank Transfer</option><option>Card</option></select></div><div class="form-field"><label>Date</label><input id="eDate" type="date" value="${new Date().toISOString().slice(0,10)}"></div><div class="form-field full"><label>Description</label><input id="eDesc"></div></div></div><div class="modal-foot"><button class="btn btn-secondary" onclick="closeModal()">Cancel</button><button class="btn btn-primary" onclick="saveExpense()">Record Expense</button></div>`)}
function saveExpense(){const amount=Number(document.getElementById('eAmount').value||0),desc=document.getElementById('eDesc').value.trim();if(amount<=0||!desc){toast('Enter an amount and description','warn');return}const e={id:`EXP-${String(93+db.expenses.length).padStart(4,'0')}`,date:document.getElementById('eDate').value,category:document.getElementById('eCat').value,description:desc,amount,method:document.getElementById('eMethod').value};db.expenses.unshift(e);addActivity('expense','Expense recorded',`${e.category} • ${money(e.amount)}`);saveDb();closeModal();render();toast('Expense recorded')}

function trackingView(){const lows=lowVariants(),pending=db.invoices.filter(i=>i.status==='Pending'),openPO=db.purchaseOrders.filter(p=>p.status!=='Received');return `<div class="section-head"><div><h2>Business Tracking</h2><p>A management action centre for stock risk, collections and incoming supply.</p></div></div><div class="tri-grid"><div class="card"><div class="card-head"><div><h3>Stock risk</h3><p>${lows.length} variant alerts</p></div></div><div class="alert-list">${lows.map(({product:p,variant:v})=>`<div class="alert-item ${v.stock===0?'critical':'warning'}"><span class="alert-dot"></span><div><b>${p.name}</b><p>${v.size} • ${v.color} • ${v.stock} left</p></div></div>`).join('')}</div></div><div class="card"><div class="card-head"><div><h3>Collections</h3><p>Invoices awaiting payment</p></div></div><div class="alert-list">${pending.map(i=>`<div class="alert-item warning"><span class="alert-dot"></span><div><b>${i.customer}</b><p>${i.id} • ${money(i.amount)} • due ${fmtDate(i.due)}</p></div></div>`).join('')||'<div class="empty-state"><p>No pending invoices.</p></div>'}</div></div><div class="card"><div class="card-head"><div><h3>Inbound stock</h3><p>Open purchase orders</p></div></div><div class="alert-list">${openPO.map(p=>`<div class="alert-item info"><span class="alert-dot"></span><div><b>${p.id} • ${p.supplier}</b><p>${p.items.reduce((a,i)=>a+i.qty,0)} units • ETA ${fmtDate(p.eta)}</p></div></div>`).join('')||'<div class="empty-state"><p>No open purchase orders.</p></div>'}</div></div></div><div class="card" style="margin-top:15px"><div class="card-head"><div><h3>Activity timeline</h3><p>Recent operational events</p></div></div><div class="activity-list">${activityHtml(db.activity)}</div></div>`}
function reportsView(){const s=stats(),cat=categorySales(),payments=paymentBreakdown(),top=topProducts();const max=Math.max(s.revenue,s.gross,s.expenses,Math.abs(s.net),1);return `<div class="section-head"><div><h2>Management Reports</h2><p>Turn sales, stock and operating costs into decision-ready business intelligence.</p></div><button class="btn btn-secondary" onclick="exportDemoData()">Export Demo JSON</button></div><div class="grid-kpis">${kpi('Revenue',money(s.revenue),'Recorded sales','↗')}${kpi('COGS',money(s.cogs),'Cost of goods sold','−')}${kpi('Gross profit',money(s.gross),`${Math.round(s.gross/Math.max(s.revenue,1)*100)}% gross margin`,'◇')}${kpi('Estimated net',money(s.net),'After demo expenses','◎',s.net<0?'down':'')}</div><div class="dashboard-grid"><div class="card"><div class="card-head"><div><h3>Profit waterfall</h3><p>How turnover converts into estimated net contribution</p></div></div><div class="profit-waterfall">${waterfall('Sales revenue',s.revenue,max)}${waterfall('Cost of goods',s.cogs,max)}${waterfall('Gross profit',s.gross,max)}${waterfall('Operating expenses',s.expenses,max)}${waterfall('Estimated net',s.net,max)}</div></div><div class="card"><div class="card-head"><div><h3>Inventory valuation</h3><p>Current stock position</p></div></div><div class="summary-list"><div class="summary-row"><span>Stock at cost</span><strong>${money(s.inventoryCost)}</strong></div><div class="summary-row"><span>Stock at retail</span><strong>${money(s.inventoryRetail)}</strong></div><div class="summary-row"><span>Potential stock margin</span><strong>${money(s.inventoryRetail-s.inventoryCost)}</strong></div><div class="summary-row"><span>Units on hand</span><strong>${s.units}</strong></div></div></div></div><div class="tri-grid" style="margin-top:15px"><div class="card"><div class="card-head"><div><h3>Sales by category</h3><p>Revenue mix</p></div></div>${miniBreakdown(cat)}</div><div class="card"><div class="card-head"><div><h3>Payment mix</h3><p>How customers paid</p></div></div>${miniBreakdown(payments)}</div><div class="card"><div class="card-head"><div><h3>Best sellers</h3><p>Units sold by product</p></div></div>${miniBreakdown(top,false)}</div></div>`}
function waterfall(name,value,max){return `<div class="waterfall-row"><label>${name}</label><div class="waterfall-bar"><i style="width:${Math.max(3,Math.abs(value)/max*100)}%"></i></div><strong>${money(value)}</strong></div>`}
function categorySales(){const o={};db.sales.forEach(s=>s.items.forEach(i=>{const p=productById(i.productId);o[p?.category||'Other']=(o[p?.category||'Other']||0)+i.price*i.qty}));return Object.entries(o).sort((a,b)=>b[1]-a[1])}
function paymentBreakdown(){const o={};db.sales.forEach(s=>o[s.method]=(o[s.method]||0)+s.total);return Object.entries(o).sort((a,b)=>b[1]-a[1])}
function topProducts(){const o={};db.sales.forEach(s=>s.items.forEach(i=>o[i.name]=(o[i.name]||0)+i.qty));return Object.entries(o).sort((a,b)=>b[1]-a[1]).slice(0,6)}
function miniBreakdown(rows,moneyMode=true){const max=Math.max(...rows.map(r=>r[1]),1);return `<div class="profit-waterfall">${rows.slice(0,6).map(([n,v])=>`<div class="waterfall-row" style="grid-template-columns:100px 1fr auto"><label>${escapeHtml(n)}</label><div class="waterfall-bar"><i style="width:${v/max*100}%"></i></div><strong style="min-width:70px">${moneyMode?money(v):v+' units'}</strong></div>`).join('')}</div>`}

function settingsView(){return `<div class="section-head"><div><h2>Admin, Users & Demo Controls</h2><p>Preview role-based permissions and manage the presentation environment.</p></div></div><div class="dashboard-grid"><div class="card"><div class="card-head"><div><h3>User access preview</h3><p>Demonstrates how production permissions can be separated</p></div></div>${userTable()}</div><div class="card"><div class="card-head"><div><h3>Demo controls</h3><p>Presentation utilities</p></div></div><div class="summary-list"><div class="summary-row"><span>Storage mode</span><strong>Browser localStorage</strong></div><div class="summary-row"><span>Current role</span><strong>${role().label}</strong></div><div class="summary-row"><span>Demo version</span><strong>Premium V3</strong></div><div class="summary-row"><span>Backend</span><strong>Not connected (demo)</strong></div></div><div style="display:grid;gap:8px;margin-top:14px"><button class="btn btn-primary" onclick="startTour()">▶ Start Guided Demo</button><button class="btn btn-secondary" onclick="exportDemoData()">Export Demo Data</button><button class="btn btn-danger" onclick="resetDemo()">Reset All Demo Data</button></div></div></div><div class="card" style="margin-top:15px"><div class="card-head"><div><h3>Production upgrade path</h3><p>What the same interface would connect to next</p></div></div><div class="tri-grid"><div class="report-metric"><span>Authentication</span><strong>Roles + Audit</strong><p class="muted" style="font-size:.68rem">Cloud identity, staff invitations, approvals and session security.</p></div><div class="report-metric"><span>Database</span><strong>Cloud Sync</strong><p class="muted" style="font-size:.68rem">Multi-device inventory, backups, branches and real-time transactions.</p></div><div class="report-metric"><span>Integrations</span><strong>Payments + WhatsApp</strong><p class="muted" style="font-size:.68rem">Mobile Money, PDF delivery, barcode scanning and automated alerts.</p></div></div></div>`}
function userTable(){return `<div class="table-wrap"><table class="data-table" style="min-width:0"><thead><tr><th>User</th><th>Email</th><th>Role</th><th>Status</th><th></th></tr></thead><tbody>${db.users.map(u=>`<tr><td><b>${escapeHtml(u.name)}</b></td><td>${escapeHtml(u.email)}</td><td>${roleConfig[u.role].label}</td><td><span class="badge badge-ok">Active</span></td><td><button class="btn btn-small btn-secondary" onclick="previewRole('${u.role}')">Preview</button></td></tr>`).join('')}</tbody></table></div>`}

const tourSteps=[
  {view:'dashboard',title:'Command Centre',text:'Start with the owner dashboard: revenue, gross profit, inventory value, stock risk, invoices and recent activity are visible in one place.'},
  {view:'pos',title:'Sell an exact fashion variant',text:'Open Point of Sale, choose a product, then select the exact size and colour. Completing a sale deducts that specific variant and creates a receipt.'},
  {view:'inventory',title:'Variant-level stock control',text:'Inventory is managed by size and colour, not just by product. Reorder alerts can identify a missing Size 38 even when other sizes remain.'},
  {view:'purchasing',title:'Turn alerts into supplier orders',text:'Low variants become reorder recommendations. Create a purchase order, then receive it to automatically replenish inventory.'},
  {view:'customers',title:'Build customer intelligence',text:'Customer profiles show spend, purchase history and segments, creating the foundation for loyalty and follow-up.'},
  {view:'invoices',title:'Manage customer billing',text:'Create branded invoices, preview them, print/save PDF, track pending balances and mark payments as received.'},
  {view:'expenses',title:'Capture operating costs',text:'Recording expenses means reports can move beyond sales and show estimated gross and net performance.'},
  {view:'reports',title:'Finish with management intelligence',text:'The report converts operational activity into revenue, COGS, gross profit, expenses, net contribution, category mix and stock valuation.'}
];
function startTour(){tourIndex=0;showTourStep()}
function showTourStep(){while(tourIndex<tourSteps.length&&!can(tourSteps[tourIndex].view))tourIndex++;if(tourIndex>=tourSteps.length){endTour();toast('Guided demo complete');return}const step=tourSteps[tourIndex];navTo(step.view);document.getElementById('tourOverlay').classList.remove('hidden');document.getElementById('tourCard').innerHTML=`<div class="tour-count">STEP ${tourIndex+1} OF ${tourSteps.length}</div><h3>${step.title}</h3><p>${step.text}</p><div class="tour-actions"><button class="btn btn-secondary" onclick="endTour()">End Tour</button><div><button class="btn btn-secondary" ${tourIndex===0?'disabled':''} onclick="previousTour()">Back</button> <button class="btn btn-primary" onclick="nextTour()">${tourIndex===tourSteps.length-1?'Finish':'Next'} →</button></div></div>`}
function nextTour(){tourIndex++;showTourStep()}
function previousTour(){tourIndex=Math.max(0,tourIndex-1);showTourStep()}
function endTour(){document.getElementById('tourOverlay').classList.add('hidden')}
function resetDemo(){if(!confirm('Reset all demo data to the original presentation state?'))return;db=clone(seed);saveDb();saleCart=[];invoiceCart=[];currentView='dashboard';renderNav();render();updateUserUI();closeModal();toast('Demo reset to original presentation state')}
function exportDemoData(){downloadText('sylvarts-demo-data.json',JSON.stringify(db,null,2),'application/json')}
function downloadText(name,text,type){const blob=new Blob([text],{type});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}