/* Sylvarts Fashion Collection — Presentation Demo V2 */
const STORE_KEY = 'sylvarts_bms_v2';
const seed = {
  products: [
    {id:1,sku:'SFC-HL-001',name:'Classic Pink Heel',category:'Heels',cost:65000,price:120000,stock:9,reorder:5},
    {id:2,sku:'SFC-HB-004',name:'Structured Handbag',category:'Handbags',cost:82000,price:155000,stock:3,reorder:4},
    {id:3,sku:'SFC-DR-011',name:'Evening Dress',category:'Dresses',cost:105000,price:220000,stock:7,reorder:3},
    {id:4,sku:'SFC-SN-007',name:'Urban Sneaker',category:'Shoes',cost:70000,price:135000,stock:0,reorder:4},
    {id:5,sku:'SFC-AC-015',name:'Statement Necklace',category:'Accessories',cost:24000,price:55000,stock:15,reorder:6},
    {id:6,sku:'SFC-SD-012',name:'Signature Sandal',category:'Sandals',cost:52000,price:98000,stock:5,reorder:5},
    {id:7,sku:'SFC-BG-009',name:'Mini Crossbody Bag',category:'Handbags',cost:54000,price:110000,stock:11,reorder:4},
    {id:8,sku:'SFC-SK-018',name:'Pleated Midi Skirt',category:'Skirts',cost:46000,price:95000,stock:6,reorder:3}
  ],
  sales:[
    {id:'S-1048',date:'2026-08-20',customer:'Walk-in Customer',method:'Mobile Money',items:[{productId:1,qty:1,price:120000}],total:120000},
    {id:'S-1047',date:'2026-08-20',customer:'Amina N.',method:'Cash',items:[{productId:5,qty:2,price:55000}],total:110000},
    {id:'S-1046',date:'2026-08-19',customer:'Sharon K.',method:'Mobile Money',items:[{productId:3,qty:1,price:220000}],total:220000},
    {id:'S-1045',date:'2026-08-19',customer:'Walk-in Customer',method:'Cash',items:[{productId:6,qty:1,price:98000}],total:98000}
  ],
  invoices:[
    {id:'INV-2026-018',date:'2026-08-20',customer:'Kampala Style Hub',amount:465000,status:'Pending',due:'2026-08-27'},
    {id:'INV-2026-017',date:'2026-08-18',customer:'Mirembe Boutique',amount:320000,status:'Paid',due:'2026-08-25'},
    {id:'INV-2026-016',date:'2026-08-17',customer:'Private Client',amount:185000,status:'Draft',due:'2026-08-24'}
  ],
  activity:[
    {type:'sale',title:'Sale S-1048 completed',detail:'Classic Pink Heel • Mobile Money',time:'Today, 09:18'},
    {type:'stock',title:'Structured Handbag is low',detail:'3 units remaining • reorder at 4',time:'Today, 08:55'},
    {type:'invoice',title:'Invoice INV-2026-018 created',detail:'Kampala Style Hub • UGX 465,000',time:'Today, 08:20'},
    {type:'stock',title:'Urban Sneaker is out of stock',detail:'Replenishment required',time:'Yesterday, 17:40'}
  ],
  daily:[180000,260000,210000,340000,295000,410000,520000,380000,610000,560000,690000,640000]
};

let db = loadDb();
let currentView = 'dashboard';
let saleCart = [];

const icons = {
  dashboard:'<svg viewBox="0 0 24 24"><rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/></svg>',
  inventory:'<svg viewBox="0 0 24 24"><path d="M4 7h16M4 12h16M4 17h16"/><path d="M7 4v16M17 4v16"/></svg>',
  sales:'<svg viewBox="0 0 24 24"><path d="M4 19V9m6 10V5m6 14v-7m4 7H2"/></svg>',
  receipts:'<svg viewBox="0 0 24 24"><path d="M6 3h12v18l-3-2-3 2-3-2-3 2z"/><path d="M9 8h6M9 12h6M9 16h4"/></svg>',
  invoices:'<svg viewBox="0 0 24 24"><path d="M6 2h9l4 4v16H6z"/><path d="M14 2v5h5M9 12h6M9 16h6"/></svg>',
  tracking:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="3"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3"/></svg>',
  reports:'<svg viewBox="0 0 24 24"><path d="M4 20V10m5 10V4m5 16v-7m5 7V7"/></svg>',
  settings:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="3"/><path d="M19 13.5v-3l-2-.7-.7-1.7.9-1.9-2.1-2.1-1.9.9-1.7-.7L10.5 2h-3l-.7 2-1.7.7-1.9-.9L1.1 5.9 2 7.8l-.7 1.7-2 .7v3l2 .7.7 1.7-.9 1.9 2.1 2.1 1.9-.9 1.7.7.7 2h3l.7-2 1.7-.7 1.9.9 2.1-2.1-.9-1.9.7-1.7z" transform="translate(2 0) scale(.85)"/></svg>'
};

function loadDb(){
  try{return JSON.parse(localStorage.getItem(STORE_KEY)) || structuredClone(seed)}catch{return JSON.parse(JSON.stringify(seed))}
}
function saveDb(){localStorage.setItem(STORE_KEY,JSON.stringify(db))}
function money(n){return 'UGX ' + Number(n||0).toLocaleString('en-UG')}
function today(){return new Date().toISOString().slice(0,10)}
function uid(prefix){return prefix+'-'+String(Date.now()).slice(-6)}
function stockState(p){if(p.stock<=0)return ['Out of stock','badge-out'];if(p.stock<=p.reorder)return ['Reorder now','badge-low'];return ['In stock','badge-ok']}
function toast(msg,type='good'){
  const wrap=document.getElementById('toastWrap'); const el=document.createElement('div');
  el.className='toast '+type; el.textContent=msg; wrap.appendChild(el); setTimeout(()=>el.remove(),3000);
}
function closeModal(){document.getElementById('modalBackdrop').classList.add('hidden')}
function openModal(html){const box=document.getElementById('modalBackdrop');document.getElementById('modal').innerHTML=html;box.classList.remove('hidden')}
function navTo(view){currentView=view;document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===view));document.getElementById('pageTitle').textContent=label(view);render();document.getElementById('sidebar').classList.remove('open')}
function label(v){return ({dashboard:'Dashboard',inventory:'Inventory',sales:'Sales',receipts:'Receipts',invoices:'Invoices',tracking:'Business Tracking',reports:'Reports',settings:'Settings'})[v]||v}

window.addEventListener('DOMContentLoaded',()=>{
  const nav=document.getElementById('sideNav');
  ['dashboard','inventory','sales','receipts','invoices','tracking','reports','settings'].forEach(v=>{
    const b=document.createElement('button'); b.className='nav-btn'+(v==='dashboard'?' active':'');b.dataset.view=v;b.innerHTML=icons[v]+`<span>${label(v)}</span>`;b.onclick=()=>navTo(v);nav.appendChild(b);
  });
  document.getElementById('menuBtn').onclick=()=>document.getElementById('sidebar').classList.toggle('open');
  document.getElementById('modalBackdrop').addEventListener('click',e=>{if(e.target.id==='modalBackdrop')closeModal()});
  render();
  setTimeout(()=>document.getElementById('loader').classList.add('is-done'),3400);
});

function render(){
  const root=document.getElementById('content');
  root.innerHTML = ({dashboard:dashboardView,inventory:inventoryView,sales:salesView,receipts:receiptsView,invoices:invoicesView,tracking:trackingView,reports:reportsView,settings:settingsView})[currentView]();
}

function stats(){
  const revenue=db.sales.reduce((a,s)=>a+s.total,0), cost=db.products.reduce((a,p)=>a+p.cost*p.stock,0), retail=db.products.reduce((a,p)=>a+p.price*p.stock,0);
  const low=db.products.filter(p=>p.stock<=p.reorder).length, pending=db.invoices.filter(i=>i.status==='Pending').reduce((a,i)=>a+i.amount,0);
  return {revenue,cost,retail,low,pending,units:db.products.reduce((a,p)=>a+p.stock,0)};
}
function hero(){const s=stats();return `<section class="hero-panel"><div><div class="hero-eyebrow">Retail Command Centre • Demo</div><h1 class="hero-title">Run Sylvarts with <span>clarity, control & style.</span></h1><p class="hero-copy">A presentation-ready business management demo for inventory, reorder decisions, sales, receipts, invoices and management reporting — designed around the Sylvarts Fashion Collection brand.</p><div class="hero-actions"><button class="btn btn-primary" onclick="openSale()">+ Record a Sale</button><button class="btn btn-secondary" onclick="navTo('inventory')">Review Inventory</button><button class="btn btn-secondary" onclick="openInvoice()">Create Invoice</button></div></div><div class="hero-stat-stack"><div class="hero-mini-stat"><span>Stock at retail</span><strong>${money(s.retail)}</strong></div><div class="hero-mini-stat"><span>Reorder attention</span><strong>${s.low} products</strong></div><div class="hero-mini-stat"><span>Outstanding invoices</span><strong>${money(s.pending)}</strong></div></div></section>`}
function kpis(){const s=stats();return `<div class="grid-kpis">
  ${kpi('Sales recorded',money(s.revenue),'↗ Demo sales value','◫')}
  ${kpi('Inventory retail value',money(s.retail),`${s.units} units available`,'◇')}
  ${kpi('Reorder attention',s.low,'Low / out-of-stock items','!')}
  ${kpi('Outstanding invoices',money(s.pending),`${db.invoices.filter(i=>i.status==='Pending').length} payment follow-up`,'▤')}
</div>`}
function kpi(label,value,sub,ico){return `<div class="kpi-card"><div class="kpi-top"><span class="kpi-label">${label}</span><span class="kpi-icon">${ico}</span></div><div class="kpi-value">${value}</div><span class="trend">${sub}</span></div>`}

function dashboardView(){
  const low=db.products.filter(p=>p.stock<=p.reorder);
  return hero()+kpis()+`<div class="dashboard-grid"><div class="card"><div class="card-head"><div><h3>Sales momentum</h3><p>Demo turnover trend across recent trading periods</p></div><span class="badge badge-ok">Live demo data</span></div><div class="chart-wrap"><div class="chart-bars">${db.daily.map(v=>`<div class="chart-bar" style="height:${Math.max(12,v/690000*100)}%" data-value="${money(v)}"></div>`).join('')}</div><div class="chart-axis">${['9','10','11','12','13','14','15','16','17','18','19','20'].map(x=>`<span>${x} Aug</span>`).join('')}</div></div></div><div class="card"><div class="card-head"><div><h3>Stock intelligence</h3><p>What needs management attention now</p></div><button class="btn btn-small btn-secondary" onclick="navTo('tracking')">View all</button></div><div class="alert-list">${low.slice(0,4).map(p=>`<div class="alert-item ${p.stock===0?'alert-critical':'alert-warning'}"><span class="alert-dot"></span><div><b>${p.name}</b><p>${p.stock===0?'Out of stock':`${p.stock} units left`} • Reorder level ${p.reorder}</p></div></div>`).join('') || '<div class="empty-state"><p>No stock alerts.</p></div>'}</div></div></div>
  <div class="dashboard-grid"><div class="card"><div class="card-head"><div><h3>Recent transactions</h3><p>Latest sales activity</p></div><button class="btn btn-small btn-secondary" onclick="navTo('sales')">All sales</button></div>${salesTable(db.sales.slice(0,5))}</div><div class="card"><div class="card-head"><div><h3>Activity feed</h3><p>Recent operational events</p></div></div><div class="activity-list">${activityHtml(db.activity.slice(0,5))}</div></div></div>`;
}

function inventoryView(){
 return `<div class="section-head"><div><h2>Inventory Management</h2><p>Stock visibility, pricing, reorder levels and product controls.</p></div><div class="toolbar"><input class="field" id="stockSearch" placeholder="Search product or SKU" oninput="filterInventory()"><select class="select" id="stockFilter" onchange="filterInventory()"><option value="all">All stock</option><option value="low">Reorder now</option><option value="out">Out of stock</option></select><button class="btn btn-secondary" onclick="exportInventory()">Export CSV</button><button class="btn btn-primary" onclick="openProduct()">+ Add product</button></div></div><div class="card"><div id="inventoryTable">${inventoryTable(db.products)}</div></div>`
}
function inventoryTable(products){return `<div class="table-wrap"><table class="data-table"><thead><tr><th>Product</th><th>SKU</th><th>Category</th><th>Cost</th><th>Price</th><th>Stock</th><th>Reorder</th><th>Status</th><th></th></tr></thead><tbody>${products.map(p=>{const st=stockState(p);return `<tr><td><div class="product-cell"><span class="product-dot">${p.name[0]}</span><b>${p.name}</b></div></td><td>${p.sku}</td><td>${p.category}</td><td>${money(p.cost)}</td><td><b>${money(p.price)}</b></td><td>${p.stock}</td><td>${p.reorder}</td><td><span class="badge ${st[1]}">${st[0]}</span></td><td><button class="btn btn-small btn-secondary" onclick="openProduct(${p.id})">Edit</button></td></tr>`}).join('')}</tbody></table></div>`}
function filterInventory(){const q=document.getElementById('stockSearch').value.toLowerCase(),f=document.getElementById('stockFilter').value;const data=db.products.filter(p=>(p.name.toLowerCase().includes(q)||p.sku.toLowerCase().includes(q)||p.category.toLowerCase().includes(q))&&(f==='all'||(f==='low'&&p.stock<=p.reorder&&p.stock>0)||(f==='out'&&p.stock===0)));document.getElementById('inventoryTable').innerHTML=inventoryTable(data)}
function openProduct(id){const p=id?db.products.find(x=>x.id===id):{name:'',sku:'',category:'',cost:'',price:'',stock:'',reorder:''};openModal(`<div class="modal-head"><div><h3>${id?'Edit product':'Add product'}</h3><div class="muted small">Inventory & reorder configuration</div></div><button class="close-btn" onclick="closeModal()">×</button></div><div class="modal-body"><div class="form-grid">${input('Product name','pName',p.name)}${input('SKU','pSku',p.sku)}${input('Category','pCategory',p.category)}${input('Cost price (UGX)','pCost',p.cost,'number')}${input('Selling price (UGX)','pPrice',p.price,'number')}${input('Current stock','pStock',p.stock,'number')}${input('Reorder level','pReorder',p.reorder,'number')}</div></div><div class="modal-foot"><button class="btn btn-secondary" onclick="closeModal()">Cancel</button><button class="btn btn-primary" onclick="saveProduct(${id||'null'})">Save product</button></div>`)}
function saveProduct(id){const obj={id:id||Date.now(),name:v('pName'),sku:v('pSku'),category:v('pCategory'),cost:+v('pCost'),price:+v('pPrice'),stock:+v('pStock'),reorder:+v('pReorder')};if(!obj.name||!obj.sku)return toast('Product name and SKU are required','warn');if(id){const i=db.products.findIndex(x=>x.id===id);db.products[i]=obj}else db.products.unshift(obj);db.activity.unshift({type:'stock',title:id?'Product updated':'Product added',detail:`${obj.name} • stock ${obj.stock}`,time:'Just now'});saveDb();closeModal();render();toast('Inventory saved')}

function salesView(){return `<div class="section-head"><div><h2>Sales & Checkout</h2><p>Record transactions and deduct stock automatically.</p></div><div class="toolbar"><button class="btn btn-primary" onclick="openSale()">+ New sale</button></div></div>${kpis()}<div class="card" style="margin-top:16px"><div class="card-head"><div><h3>Sales history</h3><p>Every completed demo transaction</p></div></div>${salesTable(db.sales)}</div>`}
function salesTable(data){return `<div class="table-wrap"><table class="data-table"><thead><tr><th>Sale</th><th>Date</th><th>Customer</th><th>Payment</th><th>Items</th><th>Total</th><th></th></tr></thead><tbody>${data.map(s=>`<tr><td><b>${s.id}</b></td><td>${s.date}</td><td>${s.customer}</td><td>${s.method}</td><td>${s.items.reduce((a,i)=>a+i.qty,0)}</td><td><b>${money(s.total)}</b></td><td><button class="btn btn-small btn-secondary" onclick="openReceipt('${s.id}')">Receipt</button></td></tr>`).join('')}</tbody></table></div>`}
function openSale(){saleCart=[];openModal(saleModal())}
function saleModal(){return `<div class="modal-head"><div><h3>New sale</h3><div class="muted small">Stock is deducted when the transaction is completed.</div></div><button class="close-btn" onclick="closeModal()">×</button></div><div class="modal-body"><div class="form-grid"><div class="form-field"><label>Customer</label><input id="saleCustomer" value="Walk-in Customer"></div><div class="form-field"><label>Payment method</label><select id="saleMethod"><option>Mobile Money</option><option>Cash</option><option>Bank Transfer</option><option>Card</option></select></div><div class="form-field full"><label>Add product</label><div style="display:flex;gap:8px"><select id="saleProduct" style="flex:1">${db.products.filter(p=>p.stock>0).map(p=>`<option value="${p.id}">${p.name} — ${money(p.price)} (${p.stock} in stock)</option>`).join('')}</select><input id="saleQty" type="number" min="1" value="1" style="width:90px"><button class="btn btn-dark" onclick="addCartItem()">Add</button></div></div></div><div id="saleCart" style="margin-top:18px">${cartHtml()}</div></div><div class="modal-foot"><button class="btn btn-secondary" onclick="closeModal()">Cancel</button><button class="btn btn-primary" onclick="completeSale()">Complete sale</button></div>`}
function addCartItem(){const id=+v('saleProduct'),qty=+v('saleQty'),p=db.products.find(x=>x.id===id);if(!p||qty<1||qty>p.stock)return toast('Check the requested quantity','warn');const existing=saleCart.find(x=>x.productId===id);if(existing){if(existing.qty+qty>p.stock)return toast('Quantity exceeds stock','warn');existing.qty+=qty}else saleCart.push({productId:id,qty,price:p.price});document.getElementById('saleCart').innerHTML=cartHtml()}
function cartHtml(){if(!saleCart.length)return `<div class="empty-state"><div class="empty-icon">＋</div><h3>Sale basket is empty</h3><p>Add one or more products above to build this transaction.</p></div>`;const total=saleCart.reduce((a,i)=>a+i.qty*i.price,0);return `<div class="table-wrap"><table class="data-table" style="min-width:0"><thead><tr><th>Item</th><th>Qty</th><th>Unit</th><th>Total</th></tr></thead><tbody>${saleCart.map(i=>{const p=db.products.find(x=>x.id===i.productId);return `<tr><td>${p.name}</td><td>${i.qty}</td><td>${money(i.price)}</td><td><b>${money(i.qty*i.price)}</b></td></tr>`}).join('')}</tbody></table></div><div class="summary-row"><span>Sale total</span><strong>${money(total)}</strong></div>`}
function completeSale(){if(!saleCart.length)return toast('Add a product to the sale','warn');for(const i of saleCart){const p=db.products.find(x=>x.id===i.productId);if(!p||p.stock<i.qty)return toast(`${p?.name||'Product'} no longer has enough stock`,'warn')}saleCart.forEach(i=>db.products.find(x=>x.id===i.productId).stock-=i.qty);const sale={id:'S-'+String(1049+db.sales.length),date:today(),customer:v('saleCustomer')||'Walk-in Customer',method:v('saleMethod'),items:JSON.parse(JSON.stringify(saleCart)),total:saleCart.reduce((a,i)=>a+i.qty*i.price,0)};db.sales.unshift(sale);db.activity.unshift({type:'sale',title:`Sale ${sale.id} completed`,detail:`${sale.customer} • ${money(sale.total)}`,time:'Just now'});saveDb();closeModal();render();toast('Sale completed and stock updated');setTimeout(()=>openReceipt(sale.id),250)}

function receiptsView(){return `<div class="section-head"><div><h2>Receipts</h2><p>Professional printable receipts generated from completed sales.</p></div></div><div class="card">${salesTable(db.sales)}</div>`}
function openReceipt(id){const s=db.sales.find(x=>x.id===id);if(!s)return;openModal(`<div class="modal-head"><div><h3>Receipt ${s.id}</h3><div class="muted small">Print-ready customer receipt</div></div><button class="close-btn" onclick="closeModal()">×</button></div><div class="modal-body doc-preview">${documentHtml('RECEIPT',s.id,s.date,s.customer,s.items.map(i=>{const p=db.products.find(x=>x.id===i.productId);return {name:p?.name||'Product',qty:i.qty,price:i.price}}),s.total,`Payment: ${s.method}`)}</div><div class="modal-foot"><button class="btn btn-secondary" onclick="closeModal()">Close</button><button class="btn btn-primary" onclick="window.print()">Print receipt</button></div>`)}

function invoicesView(){return `<div class="section-head"><div><h2>Invoices</h2><p>Create quotations/invoices and follow payment status.</p></div><button class="btn btn-primary" onclick="openInvoice()">+ Create invoice</button></div><div class="card"><div class="table-wrap"><table class="data-table"><thead><tr><th>Invoice</th><th>Date</th><th>Customer</th><th>Due</th><th>Amount</th><th>Status</th><th></th></tr></thead><tbody>${db.invoices.map(i=>`<tr><td><b>${i.id}</b></td><td>${i.date}</td><td>${i.customer}</td><td>${i.due}</td><td><b>${money(i.amount)}</b></td><td><span class="badge badge-${i.status.toLowerCase()}">${i.status}</span></td><td><button class="btn btn-small btn-secondary" onclick="previewInvoice('${i.id}')">View</button></td></tr>`).join('')}</tbody></table></div></div>`}
function openInvoice(){openModal(`<div class="modal-head"><div><h3>Create invoice</h3><div class="muted small">Demo invoice generator</div></div><button class="close-btn" onclick="closeModal()">×</button></div><div class="modal-body"><div class="form-grid">${input('Customer / business','invCustomer','')}${input('Amount (UGX)','invAmount','','number')}${input('Due date','invDue',today(),'date')}<div class="form-field"><label>Status</label><select id="invStatus"><option>Pending</option><option>Draft</option><option>Paid</option></select></div><div class="form-field full"><label>Notes / description</label><textarea id="invNotes" placeholder="Fashion items / order description"></textarea></div></div></div><div class="modal-foot"><button class="btn btn-secondary" onclick="closeModal()">Cancel</button><button class="btn btn-primary" onclick="saveInvoice()">Create invoice</button></div>`)}
function saveInvoice(){const customer=v('invCustomer'),amount=+v('invAmount');if(!customer||!amount)return toast('Customer and invoice amount are required','warn');const inv={id:'INV-2026-'+String(19+db.invoices.length).padStart(3,'0'),date:today(),customer,amount,status:v('invStatus'),due:v('invDue'),notes:v('invNotes')};db.invoices.unshift(inv);db.activity.unshift({type:'invoice',title:`Invoice ${inv.id} created`,detail:`${customer} • ${money(amount)}`,time:'Just now'});saveDb();closeModal();render();toast('Invoice created');setTimeout(()=>previewInvoice(inv.id),200)}
function previewInvoice(id){const i=db.invoices.find(x=>x.id===id);openModal(`<div class="modal-head"><div><h3>${i.id}</h3><div class="muted small">Invoice preview</div></div><button class="close-btn" onclick="closeModal()">×</button></div><div class="modal-body doc-preview">${documentHtml('INVOICE',i.id,i.date,i.customer,[{name:i.notes||'Fashion merchandise / order',qty:1,price:i.amount}],i.amount,`Due: ${i.due} • Status: ${i.status}`)}</div><div class="modal-foot"><button class="btn btn-secondary" onclick="closeModal()">Close</button><button class="btn btn-primary" onclick="window.print()">Print invoice</button></div>`)}

function trackingView(){const low=db.products.filter(p=>p.stock<=p.reorder);const pend=db.invoices.filter(i=>i.status==='Pending');return `<div class="section-head"><div><h2>Business Tracking</h2><p>Management attention board for stock, payments and activity.</p></div></div><div class="grid-kpis">${kpi('Stock alerts',low.length,'Products at or below reorder','!')}${kpi('Payment follow-up',pend.length,money(pend.reduce((a,i)=>a+i.amount,0)),'▤')}${kpi('Recorded sales',db.sales.length,'Demo transactions','↗')}${kpi('Activity events',db.activity.length,'Operational log','◎')}</div><div class="split-grid" style="margin-top:16px"><div class="card"><div class="card-head"><div><h3>Reorder board</h3><p>Prioritize products requiring replenishment</p></div></div><div class="alert-list">${low.map(p=>`<div class="alert-item ${p.stock===0?'alert-critical':'alert-warning'}"><span class="alert-dot"></span><div style="flex:1"><b>${p.name}</b><p>${p.sku} • ${p.stock} in stock • target minimum ${p.reorder}</p></div><button class="btn btn-small btn-secondary" onclick="openProduct(${p.id})">Update</button></div>`).join('')}</div></div><div class="card"><div class="card-head"><div><h3>Payment follow-up</h3><p>Invoices awaiting settlement</p></div></div><div class="summary-list">${pend.map(i=>`<div class="summary-row"><span><b style="color:var(--text)">${i.customer}</b><br>${i.id} • due ${i.due}</span><strong>${money(i.amount)}</strong></div>`).join('')||'<div class="empty-state"><p>No pending invoices.</p></div>'}</div></div></div><div class="card" style="margin-top:16px"><div class="card-head"><div><h3>Operational activity</h3><p>Demo audit-style event log</p></div></div><div class="activity-list">${activityHtml(db.activity)}</div></div>`}
function activityHtml(items){return items.map(a=>`<div class="activity"><span class="activity-icon">${a.type==='sale'?'↗':a.type==='invoice'?'▤':'◫'}</span><div><b>${a.title}</b><p>${a.detail}</p></div><time>${a.time}</time></div>`).join('')}

function reportsView(){const s=stats();const categories=[...new Set(db.products.map(p=>p.category))].map(c=>({name:c,units:db.products.filter(p=>p.category===c).reduce((a,p)=>a+p.stock,0),value:db.products.filter(p=>p.category===c).reduce((a,p)=>a+p.price*p.stock,0)}));return `<div class="section-head"><div><h2>Management Reports</h2><p>Fast demo insight into sales, inventory value and margin opportunity.</p></div><button class="btn btn-secondary" onclick="exportInventory()">Download inventory CSV</button></div><div class="grid-kpis">${kpi('Recorded revenue',money(s.revenue),'Demo transaction value','↗')}${kpi('Inventory at cost',money(s.cost),'Capital currently in stock','◇')}${kpi('Inventory at retail',money(s.retail),'Potential selling value','▥')}${kpi('Potential gross margin',money(s.retail-s.cost),'Before operating costs','+')}</div><div class="split-grid" style="margin-top:16px"><div class="card"><div class="card-head"><div><h3>Category stock position</h3><p>Units and retail value by category</p></div></div><div class="table-wrap"><table class="data-table" style="min-width:0"><thead><tr><th>Category</th><th>Units</th><th>Retail value</th></tr></thead><tbody>${categories.map(c=>`<tr><td><b>${c.name}</b></td><td>${c.units}</td><td>${money(c.value)}</td></tr>`).join('')}</tbody></table></div></div><div class="card"><div class="card-head"><div><h3>Business snapshot</h3><p>Presentation summary</p></div></div><div class="summary-list"><div class="summary-row"><span>Total product lines</span><strong>${db.products.length}</strong></div><div class="summary-row"><span>Total units in stock</span><strong>${s.units}</strong></div><div class="summary-row"><span>Products needing reorder</span><strong>${s.low}</strong></div><div class="summary-row"><span>Invoices created</span><strong>${db.invoices.length}</strong></div><div class="summary-row"><span>Outstanding receivables</span><strong>${money(s.pending)}</strong></div></div></div></div>`}
function settingsView(){return `<div class="section-head"><div><h2>Demo Settings</h2><p>Configuration controls used for presentation and testing.</p></div></div><div class="split-grid"><div class="card"><div class="card-head"><div><h3>Business profile</h3><p>Current presentation identity</p></div></div><div class="summary-list"><div class="summary-row"><span>Business</span><strong>Sylvarts Fashion Collection</strong></div><div class="summary-row"><span>Currency</span><strong>UGX</strong></div><div class="summary-row"><span>Inventory control</span><strong>Reorder level alerts</strong></div><div class="summary-row"><span>Data mode</span><strong>Browser demo storage</strong></div></div></div><div class="card"><div class="card-head"><div><h3>Demo controls</h3><p>Useful when presenting multiple times</p></div></div><p class="muted small">Resetting restores the original demo inventory, sales and invoice data on this browser.</p><button class="btn btn-danger" onclick="resetDemo()">Reset demo data</button></div></div>`}
function resetDemo(){if(!confirm('Reset this demo to its original sample data?'))return;db=JSON.parse(JSON.stringify(seed));saveDb();render();toast('Demo data reset')}

function documentHtml(type,no,date,customer,items,total,note){return `<div class="document"><div class="doc-head"><div><div class="doc-logo"><img src="Slyvarts-logo.png" alt="Sylvarts Fashion Collection"></div></div><div class="doc-title"><h2>${type}</h2><p>Sylvarts Fashion Collection<br>Kampala, Uganda</p></div></div><div class="doc-meta"><div><span>${type==='INVOICE'?'Bill to':'Customer'}</span><b>${customer}</b></div><div><span>${type} number</span><b>${no}</b><br><span>Date: ${date}</span></div></div><table class="doc-table"><thead><tr><th>Description</th><th>Qty</th><th>Unit Price</th><th>Amount</th></tr></thead><tbody>${items.map(x=>`<tr><td>${x.name}</td><td>${x.qty}</td><td>${money(x.price)}</td><td>${money(x.qty*x.price)}</td></tr>`).join('')}</tbody></table><div class="doc-total"><div class="summary-row"><span>Total</span><strong>${money(total)}</strong></div></div><div class="doc-footer">${note}<br><br>Thank you for choosing Sylvarts Fashion Collection.</div></div>`}
function input(label,id,value,type='text'){return `<div class="form-field"><label>${label}</label><input id="${id}" type="${type}" value="${String(value??'').replace(/"/g,'&quot;')}"></div>`}
function v(id){return document.getElementById(id)?.value||''}
function exportInventory(){const rows=[['SKU','Product','Category','Cost','Price','Stock','Reorder'],...db.products.map(p=>[p.sku,p.name,p.category,p.cost,p.price,p.stock,p.reorder])];const csv=rows.map(r=>r.map(x=>`"${String(x).replace(/"/g,'""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='sylvarts-inventory-demo.csv';a.click();URL.revokeObjectURL(a.href);toast('Inventory CSV prepared')}
